/**
 * External Fragrance Database
 * Edit this file to add or remove combinations.
 */

export const FRAGRANCE_DATA = [
  { id: 1, name: "High-Heat Shield", rating: 4.5, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: Sparkling ginger-citrus. Synergy: Perfect interlocking of blue ambroxan and sharp citrus.", tags: ["Turathi Blue", "Jean Lowe Immortal"], steps: "Layer 1: Turathi Blue (2 sprays) - Skin / Neck; Layer 2: Jean Lowe Immortal (3 sprays) - Clothes / Shirt" },
  { id: 2, name: "Ultimate Luxury Blue", rating: 5.0, season: "All Seasons", time_of_day: "All", occasion: "Formal", description: "Profile: Deep amber powdery blue. Synergy: Caprice's cardamom softens the sharp edges of Turathi.", tags: ["Al Nashama Caprice", "Turathi Blue"], steps: "Layer 1: Al Nashama Caprice (2 sprays) - Skin / Chest; Layer 2: Turathi Blue (2 sprays) - Clothes / Shoulders" },
  { id: 3, name: "Ginger Elysium", rating: 4.5, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: High-end effervescent lime/ginger. Synergy: Immortal boosts the bright, sparkling opening of Divin Asylum.", tags: ["Jean Lowe Immortal", "Divin Asylum"], steps: "Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Neck; Layer 2: Divin Asylum (2 sprays) - Clothes / Collar" },
  { id: 4, name: "Alpine Ocean Breeze", rating: 4.0, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: Metallic marine sea-salt air. Synergy: Milestone adds crisp marine salt to the green tea of Heaven.", tags: ["Supremacy in Heaven", "CDNI Milestone"], steps: "Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest; Layer 2: CDNI Milestone (2 sprays) - Clothes / Shirt" },
  { id: 5, name: "Modernized Emerald Vetiver", rating: 4.0, season: "Spring", time_of_day: "Day", occasion: "Office", description: "Profile: Sharp retro-modern green. Synergy: Immortal updates the heavy, dark oud-vetiver base of Ash'aa.", tags: ["Ash'aa Oud Noir", "Jean Lowe Immortal"], steps: "Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck; Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shoulders" },
  { id: 6, name: "Inky Citrus Bomb", rating: 4.0, season: "Autumn", time_of_day: "Day", occasion: "Casual", description: "Profile: Earthy dark grapefruit. Synergy: Turathi's bright grapefruit cuts through the damp ink of Encre Noire.", tags: ["Encre Noire l'Extreme", "Turathi Blue"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest; Layer 2: Turathi Blue (3 sprays) - Clothes / Shirt" },
  { id: 7, name: "Coastal Countryside", rating: 4.0, season: "Spring", time_of_day: "Day", occasion: "Casual", description: "Profile: Salty crisp ozonic green. Synergy: Milestone adds a bright oceanic breeze to the dark green landscape.", tags: ["Ash'aa Oud Noir", "CDNI Milestone"], steps: "Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck; Layer 2: CDNI Milestone (2 sprays) - Clothes / Jacket" },
  { id: 8, name: "Professional Comfort", rating: 4.5, season: "Autumn", time_of_day: "Day", occasion: "Office", description: "Profile: Creamy fig and sharp vetiver. Synergy: Liam Grey's milky tea accord perfectly balances Divin Asylum's crispness.", tags: ["Lattafa Liam Grey", "Divin Asylum"], steps: "Layer 1: Lattafa Liam Grey (2 sprays) - Skin / Neck; Layer 2: Divin Asylum (2 sprays) - Clothes / Shirt" },
  { id: 9, name: "Executive Fresh", rating: 4.5, season: "Spring", time_of_day: "Day", occasion: "Office", description: "Profile: Elite fresh-cut grass and lime. Synergy: A highly clean, professional aura with a hint of dark wood depth.", tags: ["Ash'aa Oud Noir", "Divin Asylum"], steps: "Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Chest; Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt" },
  { id: 10, name: "Upscale Ginger Cream-Soda", rating: 5.0, season: "Autumn", time_of_day: "All", occasion: "Evening", description: "Profile: Sparkling gourmand vanilla. Synergy: Ghost's rich vanilla gourmand structure is uplifted by Immortal's ginger.", tags: ["Spectre Ghost", "Jean Lowe Immortal"], steps: "Layer 1: Spectre Ghost (2 sprays) - Skin / Neck; Layer 2: Jean Lowe Immortal (3 sprays) - Clothes / Sweater" },
  { id: 11, name: "Emperor's Tea Accord", rating: 4.5, season: "Spring", time_of_day: "Day", occasion: "Office", description: "Profile: Luxury green and black tea lounge. Synergy: Liam Grey adds a dense black tea and fig richness to Heaven's silver mountain air.", tags: ["Supremacy in Heaven", "Lattafa Liam Grey"], steps: "Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest; Layer 2: Lattafa Liam Grey (3 sprays) - Clothes / Shirt" },
  { id: 12, name: "Luxury Cashmere", rating: 5.0, season: "Winter", time_of_day: "All", occasion: "Formal", description: "Profile: Niche woody shield. Synergy: Encre Noire adds an earthy framework to the soft, powdery tea of Liam Grey.", tags: ["Encre Noire l'Extreme", "Lattafa Liam Grey"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest; Layer 2: Lattafa Liam Grey (3 sprays) - Clothes / Sweater" },
  { id: 13, name: "Seductive Pineapple", rating: 4.5, season: "Spring", time_of_day: "Night", occasion: "Evening", description: "Profile: Romantic fruity pineapple spice. Synergy: Caprice introduces a sensual cardamom cloud over the bright pineapple base.", tags: ["Supremacy Collector's", "Al Nashama Caprice"], steps: "Layer 1: Supremacy Collector's (2 sprays) - Skin / Neck; Layer 2: Al Nashama Caprice (2 sprays) - Clothes / Shirt" },
  { id: 14, name: "Bad Boy in a Clean Suit", rating: 5.0, season: "Winter", time_of_day: "Night", occasion: "Evening", description: "Profile: Rugged leather and clean powder. Synergy: The masculine spice of Costume National I meets the clean powder of Caprice.", tags: ["Costume National I", "Al Nashama Caprice"], steps: "Layer 1: Costume National I (2 sprays) - Skin / Neck; Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Jacket" },
  { id: 15, name: "Freezing Powerhouse", rating: 5.0, season: "Winter", time_of_day: "Night", occasion: "Formal", description: "Profile: Smoky spicy tobacco vanilla. Synergy: Hercules provides a heavy tobacco base that anchors the airy vanilla of Ghost.", tags: ["Maison Alhambra Hercules", "Spectre Ghost"], steps: "Layer 1: Maison Alhambra Hercules (2 sprays) - Skin / Chest; Layer 2: Spectre Ghost (2 sprays) - Clothes / Heavy Coat" },
  { id: 16, name: "Spiced Chai & Tobacco", rating: 4.5, season: "Autumn", time_of_day: "All", occasion: "Casual", description: "Profile: Ultra-cozy spiced gourmand. Synergy: Hercules injects a warm cinnamon tobacco note into Liam Grey's fig-milk tea.", tags: ["Maison Alhambra Hercules", "Lattafa Liam Grey"], steps: "Layer 1: Maison Alhambra Hercules (2 sprays) - Skin / Neck; Layer 2: Lattafa Liam Grey (3 sprays) - Clothes / Shirt" },
  { id: 17, name: "Smoked Pineapple Leather", rating: 4.5, season: "Winter", time_of_day: "Night", occasion: "Evening", description: "Profile: Alpha dark fruit and leather. Synergy: SNOI's intense smoky performance perfectly overlays the rich saffron of National I.", tags: ["Costume National I", "SNOI"], steps: "Layer 1: Costume National I (2 sprays) - Skin / Chest; Layer 2: SNOI (2 sprays) - Clothes / Leather Jacket" },
  { id: 18, name: "Seductive Vanilla Leather", rating: 5.0, season: "Winter", time_of_day: "Night", occasion: "Evening", description: "Profile: Sweet rugged luxury leather. Synergy: The spicy, structural amber of National I is sweetened beautifully by Spectre Ghost.", tags: ["Costume National I", "Spectre Ghost"], steps: "Layer 1: Costume National I (2 sprays) - Skin / Neck; Layer 2: Spectre Ghost (2 sprays) - Coat" },
  { id: 19, name: "Spiced Vanilla Tobacco", rating: 4.5, season: "Autumn", time_of_day: "Night", occasion: "Evening", description: "Profile: Powdery warm tobacco lavender. Synergy: Caprice introduces a clean clean lavender note directly to Hercules' dark tobacco.", tags: ["Maison Alhambra Hercules", "Al Nashama Caprice"], steps: "Layer 1: Maison Alhambra Hercules (2 sprays) - Skin / Chest; Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Shirt" },
  { id: 20, name: "Salty Watermelon Tobacco", rating: 4.0, season: "Autumn", time_of_day: "Day", occasion: "Casual", description: "Profile: Experimental sweet-salty ozonic tobacco. Synergy: Milestone's ocean salt completely transforms the heavy sweet tobacco notes.", tags: ["Maison Alhambra Hercules", "CDNI Milestone"], steps: "Layer 1: Maison Alhambra Hercules (2 sprays) - Skin / Neck; Layer 2: CDNI Milestone (3 sprays) - Clothes / Shirt" },
  { id: 21, name: "Imperial Saffron Blue", rating: 4.5, season: "Autumn", time_of_day: "All", occasion: "Evening", description: "Profile: Exotic leathery blue amber. Synergy: National I creates an elite amber base that anchors Turathi's projecting blue notes.", tags: ["Costume National I", "Turathi Blue"], steps: "Layer 1: Costume National I (2 sprays) - Skin / Chest; Layer 2: Turathi Blue (2 sprays) - Clothes / Shirt" },
  { id: 22, name: "Midnight Metallic Ocean", rating: 4.0, season: "Summer", time_of_day: "Night", occasion: "Casual", description: "Profile: Dark fruity metallic marine. Synergy: Milestone adds crisp ozonic sea air to the heavy oakmoss/pineapple of SNOI.", tags: ["SNOI", "CDNI Milestone"], steps: "Layer 1: SNOI (2 sprays) - Skin / Neck; Layer 2: CDNI Milestone (2 sprays) - Clothes / Shoulders" },
  { id: 23, name: "Creamy Alpine Woods", rating: 4.0, season: "Spring", time_of_day: "Day", occasion: "Office", description: "Profile: Green tea smoothed by milky fig. Synergy: Heaven's sharp ink/tea edges are completely smoothed out by Liam Grey.", tags: ["Supremacy in Heaven", "Lattafa Liam Grey"], steps: "Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest; Layer 2: Lattafa Liam Grey (2 sprays) - Clothes / Shirt" },
  { id: 24, name: "Smoky Mountain Vetiver", rating: 4.0, season: "Autumn", time_of_day: "Day", occasion: "Office", description: "Profile: Dark ink vetiver meeting clean tea. Synergy: Heaven provides a clean, metallic airiness that ventilates the dark Encre Noire core.", tags: ["Encre Noire l'Extreme", "Supremacy in Heaven"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Neck; Layer 2: Supremacy in Heaven (3 sprays) - Clothes / Shirt" },
  { id: 25, name: "Absolute Universal King", rating: 5.0, season: "All Seasons", time_of_day: "All", occasion: "Casual", description: "Profile: Crowdspleasing fresh cardamom blue. Synergy: Flawless interweaving of clean corporate lavender and high-projection ambroxan.", tags: ["Al Nashama Caprice", "Turathi Blue"], steps: "Layer 1: Al Nashama Caprice (2 sprays) - Skin / Neck; Layer 2: Turathi Blue (3 sprays) - Clothes / Clothes" },
  { id: 26, name: "Aromatic Ink & Leather", rating: 4.5, season: "Winter", time_of_day: "Night", occasion: "Formal", description: "Profile: Intense ultra-masculine dark niche wood. Synergy: Pure dark art. Earthy cypress and heavy incense clashing with spiced saffron leather.", tags: ["Encre Noire l'Extreme", "Costume National I"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest; Layer 2: Costume National I (2 sprays) - Clothes / Jacket" },
  { id: 27, name: "Citrus Saffron Spark", rating: 4.0, season: "Autumn", time_of_day: "Day", occasion: "Office", description: "Profile: Leathery zesty ginger. Synergy: Immortal's ginger top note introduces a bright opening to the dry leather base.", tags: ["Costume National I", "Jean Lowe Immortal"], steps: "Layer 1: Costume National I (2 sprays) - Skin / Neck; Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shirt" },
  { id: 28, name: "Golden Pineapple Breeze", rating: 4.5, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: Premium sharp tropical pineapple. Synergy: Divin Asylum supercharges the fruity traits of the collector's edition.", tags: ["Supremacy Collector's", "Divin Asylum"], steps: "Layer 1: Supremacy Collector's (2 sprays) - Skin / Chest; Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt" },
  { id: 29, name: "Emperor's Sovereign", rating: 5.0, season: "Spring", time_of_day: "All", occasion: "Formal", description: "Profile: [3-LAYER] Deep multi-dimensional smoky pineapple. Synergy: SNOI anchors the bottom while Divin Asylum adds high-end niche sparkle to the top.", tags: ["SNOI", "Supremacy Collector's", "Divin Asylum"], steps: "Layer 1: SNOI (1 spray) - Skin / Chest; Layer 2: Supremacy Collector's (2 sprays) - Skin / Neck; Layer 3: Divin Asylum (2 sprays) - Clothes / Shoulders" },
  { id: 30, name: "Gothic Vanilla Incense", rating: 4.5, season: "Winter", time_of_day: "Night", occasion: "Formal", description: "Profile: [3-LAYER] Mysterious dark woody vanilla. Synergy: Encre Noire adds an inky darkness to Hercules' tobacco and Ghost's rich vanilla.", tags: ["Encre Noire l'Extreme", "Maison Alhambra Hercules", "Spectre Ghost"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest; Layer 2: Maison Alhambra Hercules (2 sprays) - Skin / Neck; Layer 3: Spectre Ghost (2 sprays) - Clothes / Coat" },
  { id: 31, name: "Royal Cardamom Sea", rating: 4.5, season: "Summer", time_of_day: "All", occasion: "Office", description: "Profile: [3-LAYER] Advanced aquatic-spicy fusion. Synergy: Turathi provides deep blue weight, Caprice adds spicy mid-tier fluff, Milestone freshens the top.", tags: ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone"], steps: "Layer 1: Turathi Blue (2 sprays) - Skin / Neck; Layer 2: Al Nashama Caprice (1 spray) - Skin / Chest; Layer 3: CDNI Milestone (2 sprays) - Clothes / Collar" },
  { id: 32, name: "Ultimate Zesty Aquatic", rating: 4.5, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: [3-LAYER] Extreme hot weather defense. Synergy: Unstoppable high-heat projection matrix using triple citrus-ambroxan layers.", tags: ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal"], steps: "Layer 1: Turathi Blue (2 sprays) - Skin / Neck; Layer 2: CDNI Milestone (2 sprays) - Skin / Chest; Layer 3: Jean Lowe Immortal (2 sprays) - Clothes / Shoulders" },
  { id: 33, name: "Executive Creed Tribute", rating: 4.5, season: "Spring", time_of_day: "Day", occasion: "Office", description: "Profile: [3-LAYER] Green violet leaf, pineapple, salt-air. Synergy: Classic masculine contours enhanced by modern oceanics and direct fruit sweetness.", tags: ["Ash'aa Oud Noir", "Supremacy Collector's", "CDNI Milestone"], steps: "Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck; Layer 2: Supremacy Collector's (1 spray) - Skin / Chest; Layer 3: CDNI Milestone (2 sprays) - Clothes / Shirt" },
  { id: 34, name: "Sovereign Niche Overlord", rating: 5.0, season: "Winter", time_of_day: "Night", occasion: "Formal", description: "Profile: [4-LAYER] Ultimate niche symphony of leather, tea, vetiver, vanilla. Synergy: Masterclass arrangement. Heavy, dense base elements shifting smoothly into sweet and powdery layers over time.", tags: ["Encre Noire l'Extreme", "Costume National I", "Lattafa Liam Grey", "Spectre Ghost"], steps: "Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Lower Back; Layer 2: Costume National I (2 sprays) - Skin / Chest; Layer 3: Lattafa Liam Grey (2 sprays) - Skin / Neck; Layer 4: Spectre Ghost (2 sprays) - Clothes / Coat" },
  { id: 35, name: "High-Heat Overlord", rating: 5.0, season: "Summer", time_of_day: "Day", occasion: "Casual", description: "Profile: [4-LAYER] Blockbuster summer shield of ambroxan, spice, marine salt, ginger. Synergy: Absolute armor against sweat. Designed to sequentially boil off over an 8-hour period.", tags: ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone", "Jean Lowe Immortal"], steps: "Layer 1: Turathi Blue (2 sprays) - Skin / Neck; Layer 2: Al Nashama Caprice (1 spray) - Skin / Chest; Layer 3: CDNI Milestone (2 sprays) - Clothes / Left Shoulder; Layer 4: Jean Lowe Immortal (2 sprays) - Clothes / Right Shoulder" }
];