const fragranceCombinations = [
  {
    "id": 1,
    "name": "High-Heat Shield",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Turathi Blue", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Sparkling ginger-citrus.",
    "synergy": "Perfect interlocking of blue ambroxan and sharp citrus.",
    "projection": 4.2,
    "longevity": 4.5,
    "compliment_factor": 4.4,
    "complexity": 3.8,
    "best_weather": "Sunny / High Heat",
    "best_temperature": "30°C",
    "tags": ["Turathi Blue", "Jean Lowe Immortal", "Citrus", "Ambroxan", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Turathi Blue (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (3 sprays) - Clothes / Shirt",
    "alternatives": ["Bvlgari Tygar", "Louis Vuitton L'Immensité"]
  },
  {
    "id": 2,
    "name": "Ultimate Universal King",
    "rating": 5.0,
    "season": "All Seasons",
    "time_of_day": "All",
    "occasion": "Formal",
    "fragrances": ["Al Nashama Caprice", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Deep amber powdery blue / Crowdspleasing fresh cardamom blue.",
    "synergy": "Caprice's cardamom softens the sharp edges of Turathi, creating a flawless interweaving of clean corporate lavender and high-projection ambroxan.",
    "projection": 4.8,
    "longevity": 4.7,
    "compliment_factor": 5.0,
    "complexity": 4.2,
    "best_weather": "Mild / Clear",
    "best_temperature": "20°C",
    "tags": ["Al Nashama Caprice", "Turathi Blue", "Cardamom", "Lavender", "Ambroxan"],
    "steps": "Order 1 (Deep Amber Focus):\n• Layer 1: Al Nashama Caprice (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (2 sprays) - Clothes / Shoulders\n\nOrder 2 (High-Projection Focus):\n• Layer 1: Al Nashama Caprice (2 sprays) - Skin / Neck\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Clothes",
    "alternatives": ["YSL La Nuit de l'Homme", "Bleu de Chanel"]
  },
  {
    "id": 3,
    "name": "Ginger Elysium",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Jean Lowe Immortal", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "High-end effervescent lime/ginger.",
    "synergy": "Immortal boosts the bright, sparkling opening of Divin Asylum.",
    "projection": 4.3,
    "longevity": 4.1,
    "compliment_factor": 4.6,
    "complexity": 4.0,
    "best_weather": "Warm / Sunny",
    "best_temperature": "26°C",
    "tags": ["Jean Lowe Immortal", "Divin Asylum", "Ginger", "Lime", "Elysium"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Neck\n• Layer 2: Divin Asylum (2 sprays) - Clothes / Collar",
    "alternatives": ["Roja Elysium", "Louis Vuitton L'Immensité"]
  },
  {
    "id": 4,
    "name": "Alpine Ocean Breeze",
    "rating": 4.0,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Supremacy in Heaven", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Metallic marine sea-salt air.",
    "synergy": "Milestone adds crisp marine salt to the green tea of Heaven.",
    "projection": 4.0,
    "longevity": 3.9,
    "compliment_factor": 4.1,
    "complexity": 3.7,
    "best_weather": "Warm Sea Breeze",
    "best_temperature": "28°C",
    "tags": ["Supremacy in Heaven", "CDNI Milestone", "Marine", "Sea Salt", "Green Tea"],
    "steps": "Order 1:\n• Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Silver Mountain Water", "Creed Millésime Impérial"]
  },
  {
    "id": 5,
    "name": "Modernized Emerald Vetiver",
    "rating": 4.0,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Sharp retro-modern green.",
    "synergy": "Immortal updates the heavy, dark oud-vetiver base of Ash'aa.",
    "projection": 4.1,
    "longevity": 4.4,
    "compliment_factor": 3.8,
    "complexity": 4.3,
    "best_weather": "Cool Spring Morning",
    "best_temperature": "19°C",
    "tags": ["Ash'aa Oud Noir", "Jean Lowe Immortal", "Vetiver", "Oud", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Guerlain Vetiver", "Encre Noire"]
  },
  {
    "id": 6,
    "name": "Inky Citrus Bomb",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Encre Noire l'Extreme", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Earthy dark grapefruit.",
    "synergy": "Turathi's bright grapefruit cuts through the damp ink of Encre Noire.",
    "projection": 4.2,
    "longevity": 4.3,
    "compliment_factor": 3.9,
    "complexity": 4.5,
    "best_weather": "Overcast / Rainy",
    "best_temperature": "14°C",
    "tags": ["Encre Noire l'Extreme", "Turathi Blue", "Grapefruit", "Vetiver", "Ink"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Shirt",
    "alternatives": ["Terre d'Hermès", "Encre Noire Sport"]
  },
  {
    "id": 7,
    "name": "Coastal Countryside",
    "rating": 4.0,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Ash'aa Oud Noir", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Salty crisp ozonic green.",
    "synergy": "Milestone adds a bright oceanic breeze to the dark green landscape.",
    "projection": 3.9,
    "longevity": 4.0,
    "compliment_factor": 4.0,
    "complexity": 4.1,
    "best_weather": "Breezy / Fresh",
    "best_temperature": "18°C",
    "tags": ["Ash'aa Oud Noir", "CDNI Milestone", "Ozonic", "Sea Salt", "Green Notes"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Jacket",
    "alternatives": ["Tom Ford Costa Azzurra"]
  },
  {
    "id": 8,
    "name": "Professional Comfort",
    "rating": 4.5,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Liam Grey", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Creamy fig and sharp vetiver.",
    "synergy": "Liam Grey's milky tea accord perfectly balances Divin Asylum's crispness.",
    "projection": 4.0,
    "longevity": 4.3,
    "compliment_factor": 4.5,
    "complexity": 4.2,
    "best_weather": "Cool / Crisp",
    "best_temperature": "16°C",
    "tags": ["Liam Grey", "Divin Asylum", "Fig", "Tea", "Vetiver"],
    "steps": "Order 1:\n• Layer 1: Liam Grey (2 sprays) - Skin / Neck\n• Layer 2: Divin Asylum (2 sprays) - Clothes / Shirt",
    "alternatives": ["BDK Gris Charnel"]
  },
  {
    "id": 9,
    "name": "Executive Fresh",
    "rating": 4.5,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Elite fresh-cut grass and lime.",
    "synergy": "A highly clean, professional aura with a hint of dark wood depth.",
    "projection": 4.2,
    "longevity": 4.4,
    "compliment_factor": 4.3,
    "complexity": 4.0,
    "best_weather": "Mild / Sunny",
    "best_temperature": "20°C",
    "tags": ["Ash'aa Oud Noir", "Divin Asylum", "Lime", "Green Grass", "Woody"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Chest\n• Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt",
    "alternatives": ["Tom Ford Grey Vetiver"]
  },
  {
    "id": 10,
    "name": "Upscale Ginger Cream-Soda",
    "rating": 5.0,
    "season": "Autumn",
    "time_of_day": "All",
    "occasion": "Evening",
    "fragrances": ["Spectre Ghost", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Sparkling gourmand vanilla.",
    "synergy": "Ghost's rich vanilla gourmand structure is uplifted by Immortal's ginger.",
    "projection": 4.6,
    "longevity": 4.8,
    "compliment_factor": 4.9,
    "complexity": 4.3,
    "best_weather": "Chilly Evening",
    "best_temperature": "13°C",
    "tags": ["Spectre Ghost", "Jean Lowe Immortal", "Vanilla", "Gourmand", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Spectre Ghost (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (3 sprays) - Clothes / Sweater",
    "alternatives": ["Nishane Ani", "Louis Vuitton L'Immensité"]
  },
  {
    "id": 11,
    "name": "Emperor's Tea Accord",
    "rating": 4.5,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Supremacy in Heaven", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Luxury green and black tea lounge / Green tea smoothed by milky fig.",
    "synergy": "Liam Grey adds a dense black tea and fig richness to Heaven's silver mountain air, completely smoothing out its sharp ink and tea edges.",
    "projection": 4.1,
    "longevity": 4.4,
    "compliment_factor": 4.4,
    "complexity": 4.4,
    "best_weather": "Mild / Overcast",
    "best_temperature": "17°C",
    "tags": ["Supremacy in Heaven", "Liam Grey", "Green Tea", "Black Tea", "Fig"],
    "steps": "Order 1 (Rich Dense Focus):\n• Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Shirt\n\nOrder 2 (Smoothed Out Balance):\n• Layer 1: Supremacy in Heaven (2 sprays) - Skin / Chest\n• Layer 2: Liam Grey (2 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Silver Mountain Water", "BDK Gris Charnel"]
  },
  {
    "id": 12,
    "name": "Luxury Cashmere",
    "rating": 5.0,
    "season": "Winter",
    "time_of_day": "All",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Niche woody shield.",
    "synergy": "Encre Noire adds an earthy framework to the soft, powdery tea of Liam Grey.",
    "projection": 4.3,
    "longevity": 4.7,
    "compliment_factor": 4.5,
    "complexity": 4.6,
    "best_weather": "Cold / Bitter",
    "best_temperature": "8°C",
    "tags": ["Encre Noire l'Extreme", "Liam Grey", "Cashmere", "Vetiver", "Tea"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Sweater",
    "alternatives": ["Chanel Sycomore"]
  },
  {
    "id": 13,
    "name": "Seductive Pineapple",
    "rating": 4.5,
    "season": "Spring",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Supremacy Collector's Edition", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Romantic fruity pineapple spice.",
    "synergy": "Caprice introduces a sensual cardamom cloud over the bright pineapple base.",
    "projection": 4.4,
    "longevity": 4.3,
    "compliment_factor": 4.7,
    "complexity": 3.9,
    "best_weather": "Cool Evening Breeze",
    "best_temperature": "18°C",
    "tags": ["Supremacy Collector's Edition", "Al Nashama Caprice", "Pineapple", "Cardamom", "Spicy"],
    "steps": "Order 1:\n• Layer 1: Supremacy Collector's Edition (2 sprays) - Skin / Neck\n• Layer 2: Al Nashama Caprice (2 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Aventus", "YSL La Nuit de l'Homme"]
  },
  {
    "id": 14,
    "name": "Bad Boy in a Clean Suit",
    "rating": 5.0,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Rugged leather and clean powder.",
    "synergy": "The masculine spice of Costume National I meets the clean powder of Caprice.",
    "projection": 4.7,
    "longevity": 4.8,
    "compliment_factor": 4.8,
    "complexity": 4.4,
    "best_weather": "Cold Night",
    "best_temperature": "10°C",
    "tags": ["Costume National I", "Al Nashama Caprice", "Leather", "Powdery", "Spice"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Jacket",
    "alternatives": ["Tom Ford Ombré Leather", "Dior Homme Intense"]
  },
  {
    "id": 15,
    "name": "Freezing Powerhouse",
    "rating": 5.0,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Hercules", "Spectre Ghost"],
    "fragrance_count": 2,
    "profile": "Smoky spicy tobacco vanilla.",
    "synergy": "Hercules provides a heavy tobacco base that anchors the airy vanilla of Ghost.",
    "projection": 4.9,
    "longevity": 5.0,
    "compliment_factor": 4.7,
    "complexity": 4.3,
    "best_weather": "Freezing / Frosty",
    "best_temperature": "4°C",
    "tags": ["Hercules", "Spectre Ghost", "Tobacco", "Vanilla", "Smoky"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Chest\n• Layer 2: Spectre Ghost (2 sprays) - Clothes / Heavy Coat",
    "alternatives": ["Parfums de Marly Herod", "Nishane Ani"]
  },
  {
    "id": 16,
    "name": "Spiced Chai & Tobacco",
    "rating": 4.5,
    "season": "Autumn",
    "time_of_day": "All",
    "occasion": "Casual",
    "fragrances": ["Hercules", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Ultra-cozy spiced gourmand.",
    "synergy": "Hercules injects a warm cinnamon tobacco note into Liam Grey's fig-milk tea.",
    "projection": 4.2,
    "longevity": 4.6,
    "compliment_factor": 4.6,
    "complexity": 4.3,
    "best_weather": "Crisp / Autumn Chill",
    "best_temperature": "12°C",
    "tags": ["Hercules", "Liam Grey", "Chai", "Tobacco", "Cinnamon"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Neck\n• Layer 2: Liam Grey (3 sprays) - Clothes / Shirt",
    "alternatives": ["Tom Ford Tobacco Vanille"]
  },
  {
    "id": 17,
    "name": "Smoked Pineapple Leather",
    "rating": 4.5,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "SNOI"],
    "fragrance_count": 2,
    "profile": "Alpha dark fruit and leather.",
    "synergy": "SNOI's intense smoky performance perfectly overlays the rich saffron of National I.",
    "projection": 4.8,
    "longevity": 4.9,
    "compliment_factor": 4.5,
    "complexity": 4.5,
    "best_weather": "Cold / Clear Night",
    "best_temperature": "9°C",
    "tags": ["Costume National I", "SNOI", "Leather", "Pineapple", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Chest\n• Layer 2: SNOI (2 sprays) - Clothes / Leather Jacket",
    "alternatives": ["Nishane Hacivat", "Creed Aventus"]
  },
  {
    "id": 18,
    "name": "Seductive Vanilla Leather",
    "rating": 5.0,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Spectre Ghost"],
    "fragrance_count": 2,
    "profile": "Sweet rugged luxury leather.",
    "synergy": "The spicy, structural amber of National I is sweetened beautifully by Spectre Ghost.",
    "projection": 4.6,
    "longevity": 4.8,
    "compliment_factor": 4.9,
    "complexity": 4.2,
    "best_weather": "Freezing / Severe Cold",
    "best_temperature": "7°C",
    "tags": ["Costume National I", "Spectre Ghost", "Leather", "Vanilla", "Amber"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Spectre Ghost (2 sprays) - Coat",
    "alternatives": ["Tom Ford Ombré Leather", "Nishane Ani"]
  },
  {
    "id": 19,
    "name": "Spiced Vanilla Tobacco",
    "rating": 4.5,
    "season": "Autumn",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Hercules", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Powdery warm tobacco lavender.",
    "synergy": "Caprice introduces a clean clean lavender note directly to Hercules' dark tobacco.",
    "projection": 4.3,
    "longevity": 4.5,
    "compliment_factor": 4.4,
    "complexity": 4.1,
    "best_weather": "Cool / Windy",
    "best_temperature": "14°C",
    "tags": ["Hercules", "Al Nashama Caprice", "Tobacco", "Lavender", "Powdery"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Chest\n• Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Shirt",
    "alternatives": ["Parfums de Marly Herod"]
  },
  {
    "id": 20,
    "name": "Salty Watermelon Tobacco",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Hercules", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Experimental sweet-salty ozonic tobacco.",
    "synergy": "Milestone's ocean salt completely transforms the heavy sweet tobacco notes.",
    "projection": 4.1,
    "longevity": 4.2,
    "compliment_factor": 4.0,
    "complexity": 4.7,
    "best_weather": "Mild Autumn Day",
    "best_temperature": "16°C",
    "tags": ["Hercules", "CDNI Milestone", "Tobacco", "Sea Salt", "Watermelon"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (3 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Millésime Impérial"]
  },
  {
    "id": 21,
    "name": "Imperial Saffron Blue",
    "rating": 4.5,
    "season": "Autumn",
    "time_of_day": "All",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Exotic leathery blue amber.",
    "synergy": "National I creates an elite amber base that anchors Turathi's projecting blue notes.",
    "projection": 4.5,
    "longevity": 4.6,
    "compliment_factor": 4.5,
    "complexity": 4.3,
    "best_weather": "Cool / Clear",
    "best_temperature": "15°C",
    "tags": ["Costume National I", "Turathi Blue", "Saffron", "Amber", "Blue"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (2 sprays) - Clothes / Shirt",
    "alternatives": ["Tom Ford Ombré Leather", "Bvlgari Tygar"]
  },
  {
    "id": 22,
    "name": "Midnight Metallic Ocean",
    "rating": 4.0,
    "season": "Summer",
    "time_of_day": "Night",
    "occasion": "Casual",
    "fragrances": ["SNOI", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Dark fruity metallic marine.",
    "synergy": "Milestone adds crisp ozonic sea air to the heavy oakmoss/pineapple of SNOI.",
    "projection": 4.3,
    "longevity": 4.3,
    "compliment_factor": 4.2,
    "complexity": 3.9,
    "best_weather": "Warm Summer Night",
    "best_temperature": "24°C",
    "tags": ["SNOI", "CDNI Milestone", "Marine", "Pineapple", "Oakmoss"],
    "steps": "Order 1:\n• Layer 1: SNOI (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Office For Men"]
  },
  {
    "id": 23,
    "name": "Smoky Mountain Vetiver",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Encre Noire l'Extreme", "Supremacy in Heaven"],
    "fragrance_count": 2,
    "profile": "Dark ink vetiver meeting clean tea.",
    "synergy": "Heaven provides a clean, metallic airiness that ventilates the dark Encre Noire core.",
    "projection": 4.0,
    "longevity": 4.2,
    "compliment_factor": 3.7,
    "complexity": 4.5,
    "best_weather": "Damp / Foggy",
    "best_temperature": "13°C",
    "tags": ["Encre Noire l'Extreme", "Supremacy in Heaven", "Vetiver", "Ink", "Green Tea"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Neck\n• Layer 2: Supremacy in Heaven (3 sprays) - Clothes / Shirt",
    "alternatives": ["Chanel Sycomore"]
  },
  {
    "id": 24,
    "name": "Aromatic Ink & Leather",
    "rating": 4.5,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Costume National I"],
    "fragrance_count": 2,
    "profile": "Intense ultra-masculine dark niche wood.",
    "synergy": "Pure dark art. Earthy cypress and heavy incense clashing with spiced saffron leather.",
    "projection": 4.6,
    "longevity": 4.9,
    "compliment_factor": 3.8,
    "complexity": 4.8,
    "best_weather": "Freezing Night",
    "best_temperature": "5°C",
    "tags": ["Encre Noire l'Extreme", "Costume National I", "Cypress", "Incense", "Leather"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Costume National I (2 sprays) - Clothes / Jacket",
    "alternatives": ["Amouage Interlude Man"]
  },
  {
    "id": 25,
    "name": "Citrus Saffron Spark",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Costume National I", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Leathery zesty ginger.",
    "synergy": "Immortal's ginger top note introduces a bright opening to the dry leather base.",
    "projection": 4.2,
    "longevity": 4.5,
    "compliment_factor": 4.1,
    "complexity": 4.2,
    "best_weather": "Crisp Morning",
    "best_temperature": "14°C",
    "tags": ["Costume National I", "Jean Lowe Immortal", "Leather", "Ginger", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shirt",
    "alternatives": ["Tom Ford Ombré Leather"]
  },
  {
    "id": 26,
    "name": "Golden Pineapple Breeze",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Supremacy Collector's Edition", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Premium sharp tropical pineapple.",
    "synergy": "Divin Asylum supercharges the fruity traits of the collector's edition.",
    "projection": 4.4,
    "longevity": 4.2,
    "compliment_factor": 4.7,
    "complexity": 3.8,
    "best_weather": "Sunny / High Heat",
    "best_temperature": "26°C",
    "tags": ["Supremacy Collector's Edition", "Divin Asylum", "Pineapple", "Tropical", "Citrus"],
    "steps": "Order 1:\n• Layer 1: Supremacy Collector's Edition (2 sprays) - Skin / Chest\n• Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Aventus", "Roja Elysium"]
  },
  {
    "id": 27,
    "name": "Emperor's Sovereign",
    "rating": 5.0,
    "season": "Spring",
    "time_of_day": "All",
    "occasion": "Formal",
    "fragrances": ["SNOI", "Supremacy Collector's Edition", "Divin Asylum"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Deep multi-dimensional smoky pineapple.",
    "synergy": "SNOI anchors the bottom while Divin Asylum adds high-end niche sparkle to the top.",
    "projection": 4.7,
    "longevity": 4.8,
    "compliment_factor": 4.9,
    "complexity": 4.6,
    "best_weather": "Clear / Pleasant",
    "best_temperature": "18°C",
    "tags": ["SNOI", "Supremacy Collector's Edition", "Divin Asylum", "Pineapple", "Smoky"],
    "steps": "Order 1:\n• Layer 1: SNOI (1 spray) - Skin / Chest\n• Layer 2: Supremacy Collector's Edition (2 sprays) - Skin / Neck\n• Layer 3: Divin Asylum (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Creed Aventus Extrait"]
  },
  {
    "id": 28,
    "name": "Gothic Vanilla Incense",
    "rating": 4.5,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Hercules", "Spectre Ghost"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Mysterious dark woody vanilla.",
    "synergy": "Encre Noire adds an inky darkness to Hercules' tobacco and Ghost's rich vanilla.",
    "projection": 4.4,
    "longevity": 4.8,
    "compliment_factor": 4.2,
    "complexity": 4.8,
    "best_weather": "Cold / Dark Overcast",
    "best_temperature": "6°C",
    "tags": ["Encre Noire l'Extreme", "Hercules", "Spectre Ghost", "Vanilla", "Incense"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Hercules (2 sprays) - Skin / Neck\n• Layer 3: Spectre Ghost (2 sprays) - Clothes / Coat",
    "alternatives": ["Amouage Memoir Man"]
  },
  {
    "id": 29,
    "name": "Royal Cardamom Sea",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "All",
    "occasion": "Office",
    "fragrances": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Advanced aquatic-spicy fusion.",
    "synergy": "Turathi provides deep blue weight, Caprice adds spicy mid-tier fluff, Milestone freshens the top.",
    "projection": 4.5,
    "longevity": 4.4,
    "compliment_factor": 4.6,
    "complexity": 4.3,
    "best_weather": "Hot / Humid",
    "best_temperature": "27°C",
    "tags": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone", "Aquatic", "Cardamom"],
    "steps": "Order 1:\n• Layer 1: Turathi Blue (2 sprays) - Skin / Neck\n• Layer 2: Al Nashama Caprice (1 spray) - Skin / Chest\n• Layer 3: CDNI Milestone (2 sprays) - Clothes / Collar",
    "alternatives": ["Bleu de Chanel Parfum"]
  },
  {
    "id": 30,
    "name": "Ultimate Zesty Aquatic",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Extreme hot weather defense.",
    "synergy": "Unstoppable high-heat projection matrix using triple citrus-ambroxan layers.",
    "projection": 4.7,
    "longevity": 4.6,
    "compliment_factor": 4.5,
    "complexity": 3.9,
    "best_weather": "Extreme Heat",
    "best_temperature": "32°C",
    "tags": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal", "Aquatic", "Citrus"],
    "steps": "Order 1:\n• Layer 1: Turathi Blue (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (2 sprays) - Skin / Chest\n• Layer 3: Jean Lowe Immortal (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Bvlgari Tygar"]
  },
  {
    "id": 31,
    "name": "Executive Creed Tribute",
    "rating": 4.5,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Supremacy Collector's Edition", "CDNI Milestone"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Green violet leaf, pineapple, salt-air.",
    "synergy": "Classic masculine contours enhanced by modern oceanics and direct fruit sweetness.",
    "projection": 4.3,
    "longevity": 4.4,
    "compliment_factor": 4.4,
    "complexity": 4.2,
    "best_weather": "Bright / Sunny",
    "best_temperature": "19°C",
    "tags": ["Ash'aa Oud Noir", "Supremacy Collector's Edition", "CDNI Milestone", "Violet Leaf", "Pineapple"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: Supremacy Collector's Edition (1 spray) - Skin / Chest\n• Layer 3: CDNI Milestone (2 sprays) - Clothes / Shirt",
    "alternatives": ["Creed Green Irish Tweed"]
  },
  {
    "id": 32,
    "name": "Sovereign Niche Overlord",
    "rating": 5.0,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Costume National I", "Liam Grey", "Spectre Ghost"],
    "fragrance_count": 4,
    "profile": "[4-LAYER] Ultimate niche symphony of leather, tea, vetiver, vanilla.",
    "synergy": "Masterclass arrangement. Heavy, dense base elements shifting smoothly into sweet and powdery layers over time.",
    "projection": 4.8,
    "longevity": 5.0,
    "compliment_factor": 4.6,
    "complexity": 5.0,
    "best_weather": "Extreme Cold / Frosty",
    "best_temperature": "4°C",
    "tags": ["Encre Noire l'Extreme", "Costume National I", "Liam Grey", "Spectre Ghost", "Leather"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Lower Back\n• Layer 2: Costume National I (2 sprays) - Skin / Chest\n• Layer 3: Liam Grey (2 sprays) - Skin / Neck\n• Layer 4: Spectre Ghost (2 sprays) - Clothes / Coat",
    "alternatives": ["Amouage Interlude Man"]
  },
  {
    "id": 33,
    "name": "High-Heat Overlord",
    "rating": 5.0,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone", "Jean Lowe Immortal"],
    "fragrance_count": 4,
    "profile": "[4-LAYER] Blockbuster summer shield of ambroxan, spice, marine salt, ginger.",
    "synergy": "Absolute armor against sweat. Designed to sequentially boil off over an 8-hour period.",
    "projection": 5.0,
    "longevity": 4.9,
    "compliment_factor": 4.8,
    "complexity": 4.4,
    "best_weather": "Scorching Heat",
    "best_temperature": "35°C",
    "tags": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone", "Jean Lowe Immortal", "Ambroxan"],
    "steps": "Order 1:\n• Layer 1: Turathi Blue (2 sprays) - Skin / Neck\n• Layer 2: Al Nashama Caprice (1 spray) - Skin / Chest\n• Layer 3: CDNI Milestone (2 sprays) - Clothes / Left Shoulder\n• Layer 4: Jean Lowe Immortal (2 sprays) - Clothes / Right Shoulder",
    "alternatives": ["Bvlgari Tygar Ultra"]
  }
];