export const fragranceCombinations = [
  {
    "id": 1,
    "name": "High-Heat Shield",
    "rating": 4.3,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Jean Lowe Immortal", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Sparkling ginger-citrus with radiant ambroxan.",
    "dominant_notes": ["Grapefruit", "Ginger", "Ambroxan", "Bergamot"],
    "synergy": "Immortal's ginger-grapefruit-ambroxan base fuses seamlessly with Turathi Blue's citrus-ambroxan bomb, creating a layered high-projection citrus shield.",
    "projection": 4.5,
    "longevity": 4.4,
    "compliment_factor": 4.4,
    "complexity": 3.8,
    "best_weather": "Sunny / High Heat",
    "best_temperature": "26°C–36°C",
    "tags": ["Turathi Blue", "Jean Lowe Immortal", "Citrus", "Ambroxan", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Shirt",
    "alternatives": ["Turathi Blue", "Ultimate Zesty Aquatic"]
  },
  {
    "id": 2,
    "name": "Ultimate Universal King",
    "rating": 4.7,
    "season": "Spring / Autumn / Winter",
    "time_of_day": "All",
    "occasion": "Office / Evening",
    "fragrances": ["Al Nashama Caprice", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Fresh cardamom-spice with radiant blue ambroxan.",
    "dominant_notes": ["Cardamom", "Lavender", "Ambroxan", "Grapefruit"],
    "synergy": "Caprice's warm spiced cardamom and lavender heart softens and anchors Turathi Blue's projecting citrus-ambroxan, creating a well-rounded aromatic-fresh hybrid that reads expensive at moderate temperatures.",
    "projection": 4.6,
    "longevity": 4.5,
    "compliment_factor": 4.8,
    "complexity": 4.2,
    "best_weather": "Mild to Cool / Clear",
    "best_temperature": "10°C–24°C",
    "tags": ["Al Nashama Caprice", "Turathi Blue", "Cardamom", "Lavender", "Ambroxan"],
    "steps": "Order 1 (Deep Amber Focus):\n• Layer 1: Al Nashama Caprice (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (2 sprays) - Clothes / Shoulders\n\nOrder 2 (High-Projection Focus):\n• Layer 1: Al Nashama Caprice (2 sprays) - Skin / Neck\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Shirt",
    "alternatives": ["Al Nashama Caprice", "Turathi Blue", "High-Heat Overlord"]
  },
  {
    "id": 3,
    "name": "Ginger Elysium",
    "rating": 4.4,
    "season": "Spring / Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Jean Lowe Immortal", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "High-end effervescent ginger-citrus.",
    "dominant_notes": ["Ginger", "Lime", "Grapefruit", "Ambroxan"],
    "synergy": "Immortal's ginger and ambroxan base boosts the bright, sparkling multi-citrus opening of Divin Asylum, adding longevity to Divin Asylum's known performance weakness.",
    "projection": 4.3,
    "longevity": 4.2,
    "compliment_factor": 4.5,
    "complexity": 4.0,
    "best_weather": "Warm / Sunny",
    "best_temperature": "22°C–32°C",
    "tags": ["Jean Lowe Immortal", "Divin Asylum", "Ginger", "Lime", "Elysium"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Chest\n• Layer 2: Divin Asylum (2 sprays) - Clothes / Collar",
    "alternatives": ["Divin Asylum", "Jean Lowe Immortal", "High-Heat Shield"]
  },
  {
    "id": 4,
    "name": "Alpine Ocean Breeze",
    "rating": 4.0,
    "season": "Spring / Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Supremacy In Heaven", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Metallic green tea over fresh marine sea-salt.",
    "dominant_notes": ["Green Tea", "Blackcurrant", "Sea Notes", "Violet"],
    "synergy": "Milestone's salt-and-violet marine character adds an ozonic coastal freshness to the crisp green tea and sharp blackcurrant of Supremacy In Heaven.",
    "projection": 3.9,
    "longevity": 3.9,
    "compliment_factor": 4.0,
    "complexity": 3.7,
    "best_weather": "Warm Sea Breeze",
    "best_temperature": "24°C–34°C",
    "tags": ["Supremacy In Heaven", "CDNI Milestone", "Marine", "Sea Notes", "Green Tea"],
    "steps": "Order 1:\n• Layer 1: Supremacy In Heaven (2 sprays) - Skin / Chest\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Shirt",
    "alternatives": ["Supremacy In Heaven", "CDNI Milestone", "Midnight Metallic Ocean"]
  },
  {
    "id": 5,
    "name": "Modernized Emerald Vetiver",
    "rating": 4.0,
    "season": "Spring / Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Sharp retro-modern green with a ginger-ambroxan lift.",
    "dominant_notes": ["Bergamot", "Juniper Berry", "Ginger", "Grapefruit"],
    "synergy": "Immortal's ginger-grapefruit-ambroxan opening modernises the crisp green juniper and violet character of Ash'aa Oud Noir, giving it a contemporary freshness that reads well in professional settings.",
    "projection": 4.1,
    "longevity": 4.3,
    "compliment_factor": 3.9,
    "complexity": 4.2,
    "best_weather": "Cool Spring / Autumn Morning",
    "best_temperature": "14°C–24°C",
    "tags": ["Ash'aa Oud Noir", "Jean Lowe Immortal", "Bergamot", "Juniper", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Encre Noire l'Extreme", "Executive Fresh"]
  },
  {
    "id": 6,
    "name": "Inky Citrus Bomb",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Encre Noire l'Extreme", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Earthy dark vetiver-cypress with grapefruit luminosity.",
    "dominant_notes": ["Grapefruit", "Vetiver", "Cypress", "Ambroxan"],
    "synergy": "Turathi Blue's bright grapefruit and ambroxan cuts through the damp, inky cypress-vetiver of Encre Noire l'Extreme, making the dark fragrance wearable in daylight hours.",
    "projection": 4.2,
    "longevity": 4.4,
    "compliment_factor": 3.9,
    "complexity": 4.5,
    "best_weather": "Overcast / Rainy",
    "best_temperature": "10°C–18°C",
    "tags": ["Encre Noire l'Extreme", "Turathi Blue", "Grapefruit", "Vetiver", "Ink"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Shirt",
    "alternatives": ["Encre Noire l'Extreme", "Turathi Blue", "Smoky Mountain Vetiver"]
  },
  {
    "id": 7,
    "name": "Coastal Countryside",
    "rating": 4.0,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Ash'aa Oud Noir", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Crisp ozonic marine green.",
    "dominant_notes": ["Sea Notes", "Violet", "Juniper Berry", "Bergamot"],
    "synergy": "Milestone adds a bright ozonic sea-salt and violet breeze to the clean green juniper and bergamot character of Ash'aa Oud Noir.",
    "projection": 3.9,
    "longevity": 4.0,
    "compliment_factor": 4.0,
    "complexity": 4.0,
    "best_weather": "Breezy / Fresh",
    "best_temperature": "16°C–26°C",
    "tags": ["Ash'aa Oud Noir", "CDNI Milestone", "Ozonic", "Sea Notes", "Green Notes"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Jacket",
    "alternatives": ["CDNI Milestone", "Midnight Metallic Ocean", "Executive Creed Tribute"]
  },
  {
    "id": 8,
    "name": "Professional Comfort",
    "rating": 4.4,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Liam Grey", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Creamy fig and black tea with a citrus lift.",
    "dominant_notes": ["Fig", "Black Tea", "Cardamom", "Lime", "Grapefruit"],
    "synergy": "Liam Grey's dense, milky fig and black tea accord provides a sophisticated base that anchors and extends the sparkling but fleeting multi-citrus of Divin Asylum.",
    "projection": 4.0,
    "longevity": 4.3,
    "compliment_factor": 4.5,
    "complexity": 4.2,
    "best_weather": "Cool / Crisp",
    "best_temperature": "12°C–20°C",
    "tags": ["Liam Grey", "Divin Asylum", "Fig", "Tea", "Citrus"],
    "steps": "Order 1:\n• Layer 1: Liam Grey (2 sprays) - Skin / Neck\n• Layer 2: Divin Asylum (2 sprays) - Clothes / Shirt",
    "alternatives": ["Liam Grey", "Emperor's Tea Accord"]
  },
  {
    "id": 9,
    "name": "Executive Fresh",
    "rating": 4.4,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Elite fresh-cut green with sparkling lime-grapefruit.",
    "dominant_notes": ["Lime", "Grapefruit", "Bergamot", "Juniper Berry", "Violet"],
    "synergy": "The precise, tailored green-juniper freshness of Ash'aa Oud Noir pairs beautifully with Divin Asylum's elite multi-citrus, creating a polished professional aura with genuine depth.",
    "projection": 4.2,
    "longevity": 4.3,
    "compliment_factor": 4.3,
    "complexity": 4.0,
    "best_weather": "Mild / Sunny",
    "best_temperature": "14°C–24°C",
    "tags": ["Ash'aa Oud Noir", "Divin Asylum", "Lime", "Grapefruit", "Green"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Chest\n• Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt",
    "alternatives": ["Divin Asylum", "Modernized Emerald Vetiver", "Executive Creed Tribute"]
  },
  {
    "id": 10,
    "name": "Upscale Ginger Cream-Soda",
    "rating": 4.7,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Spectre Ghost", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Sparkling gourmand vanilla with zingy ginger.",
    "dominant_notes": ["Vanilla", "Ginger", "Bergamot", "Ambroxan"],
    "synergy": "Ghost's rich, creamy vanilla-cardamom base is uplifted and made wearable by Immortal's zingy ginger-grapefruit top, creating a gourmand scent that wears with unexpected vibrancy rather than heaviness.",
    "projection": 4.4,
    "longevity": 4.6,
    "compliment_factor": 4.8,
    "complexity": 4.3,
    "best_weather": "Cool / Chilly Evening",
    "best_temperature": "8°C–18°C",
    "tags": ["Spectre Ghost", "Jean Lowe Immortal", "Vanilla", "Gourmand", "Ginger"],
    "steps": "Order 1:\n• Layer 1: Spectre Ghost (2 sprays) - Skin / Chest\n• Layer 2: Jean Lowe Immortal (3 sprays) - Clothes / Sweater",
    "alternatives": ["Spectre Ghost", "Jean Lowe Immortal", "Seductive Vanilla Leather"]
  },
  {
    "id": 11,
    "name": "Emperor's Tea Accord",
    "rating": 4.4,
    "season": "Spring / Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Supremacy In Heaven", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Green tea lounge smoothed by milky fig and black tea.",
    "dominant_notes": ["Green Tea", "Black Tea", "Fig", "Cardamom", "Blackcurrant"],
    "synergy": "Liam Grey's dense fig and black tea richness smooths and deepens the sharp blackcurrant-green tea character of Supremacy In Heaven, transforming it from a fresh linear fragrance into a complex tea accord.",
    "projection": 4.0,
    "longevity": 4.4,
    "compliment_factor": 4.3,
    "complexity": 4.4,
    "best_weather": "Mild / Overcast",
    "best_temperature": "12°C–22°C",
    "tags": ["Supremacy In Heaven", "Liam Grey", "Green Tea", "Black Tea", "Fig"],
    "steps": "Order 1 (Rich Dense Focus):\n• Layer 1: Supremacy In Heaven (2 sprays) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Shirt\n\nOrder 2 (Smoothed Out Balance):\n• Layer 1: Supremacy In Heaven (2 sprays) - Skin / Chest\n• Layer 2: Liam Grey (2 sprays) - Clothes / Shirt",
    "alternatives": ["Supremacy In Heaven", "Liam Grey", "Professional Comfort"]
  },
  {
    "id": 12,
    "name": "Luxury Cashmere",
    "rating": 4.6,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Formal / Evening",
    "fragrances": ["Encre Noire l'Extreme", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Dark woody vetiver softened by creamy fig and tea.",
    "dominant_notes": ["Vetiver", "Cypress", "Fig", "Black Tea", "Incense"],
    "synergy": "Liam Grey's powdery, creamy fig and black tea accord dramatically softens and makes accessible the dark, avant-garde vetiver-cypress-incense of Encre Noire l'Extreme, resulting in a deeply wearable niche character.",
    "projection": 4.2,
    "longevity": 4.7,
    "compliment_factor": 4.5,
    "complexity": 4.6,
    "best_weather": "Cold / Bitter",
    "best_temperature": "2°C–14°C",
    "tags": ["Encre Noire l'Extreme", "Liam Grey", "Cashmere", "Vetiver", "Tea"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Sweater",
    "alternatives": ["Liam Grey", "Encre Noire l'Extreme", "Sovereign Niche Overlord"]
  },
  {
    "id": 13,
    "name": "Seductive Pineapple",
    "rating": 4.4,
    "season": "Spring / Autumn",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Supremacy Collector's Edition", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Romantic fruity pineapple-cardamom spice.",
    "dominant_notes": ["Pineapple", "Cardamom", "Lavender", "Ginger", "Oakmoss"],
    "synergy": "Caprice introduces a sensual, warm cardamom-lavender cloud that drapes over the crisp, fresh pineapple and bergamot of the Collector's Edition, creating a more romantic and evening-oriented character.",
    "projection": 4.3,
    "longevity": 4.2,
    "compliment_factor": 4.7,
    "complexity": 3.9,
    "best_weather": "Cool Evening Breeze",
    "best_temperature": "12°C–22°C",
    "tags": ["Supremacy Collector's Edition", "Al Nashama Caprice", "Pineapple", "Cardamom", "Spicy"],
    "steps": "Order 1:\n• Layer 1: Supremacy Collector's Edition (2 sprays) - Skin / Chest\n• Layer 2: Al Nashama Caprice (2 sprays) - Clothes / Shirt",
    "alternatives": ["SNOI (Supremacy Not Only Intense)", "Al Nashama Caprice", "Emperor's Sovereign"]
  },
  {
    "id": 14,
    "name": "Bad Boy in a Clean Suit",
    "rating": 4.8,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Saffron-leather and clean cardamom powder.",
    "dominant_notes": ["Saffron", "Leather", "Cardamom", "Lavender", "Ambroxan"],
    "synergy": "The bold saffron-leather-ambroxan character of Costume National I meets the clean cardamom-lavender of Caprice. The result is a refined masculine contrast — dark intensity with a powdery, elegant top.",
    "projection": 4.6,
    "longevity": 4.7,
    "compliment_factor": 4.8,
    "complexity": 4.4,
    "best_weather": "Cold Night",
    "best_temperature": "4°C–16°C",
    "tags": ["Costume National I", "Al Nashama Caprice", "Leather", "Powdery", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Jacket",
    "alternatives": ["Costume National I", "Al Nashama Caprice", "Seductive Vanilla Leather"]
  },
  {
    "id": 15,
    "name": "Freezing Powerhouse",
    "rating": 4.7,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal / Evening",
    "fragrances": ["Hercules", "Spectre Ghost"],
    "fragrance_count": 2,
    "profile": "Sweet spiced tobacco wrapped in warm vanilla.",
    "dominant_notes": ["Tobacco", "Vanilla", "Cinnamon", "Incense", "Cardamom"],
    "synergy": "Hercules' rich cinnamon-tobacco-incense foundation provides a dense, grounding base that Spectre Ghost's ginger-cardamom-vanilla structure builds beautifully upon, creating an enveloping cold-weather comfort scent.",
    "projection": 4.5,
    "longevity": 4.8,
    "compliment_factor": 4.7,
    "complexity": 4.4,
    "best_weather": "Freezing / Frosty",
    "best_temperature": "0°C–10°C",
    "tags": ["Hercules", "Spectre Ghost", "Tobacco", "Vanilla", "Cinnamon"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Chest\n• Layer 2: Spectre Ghost (2 sprays) - Clothes / Heavy Coat",
    "alternatives": ["Hercules", "Spectre Ghost", "Gothic Vanilla Incense"]
  },
  {
    "id": 16,
    "name": "Spiced Chai & Tobacco",
    "rating": 4.4,
    "season": "Autumn / Winter",
    "time_of_day": "All",
    "occasion": "Casual",
    "fragrances": ["Hercules", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Ultra-cozy spiced gourmand tobacco and fig tea.",
    "dominant_notes": ["Tobacco", "Vanilla", "Cinnamon", "Fig", "Black Tea"],
    "synergy": "Hercules injects warm cinnamon-tobacco and osmanthus depth into Liam Grey's creamy fig-milk tea structure, creating a chai-like comfort accord with longevity from both fragrances.",
    "projection": 4.1,
    "longevity": 4.6,
    "compliment_factor": 4.5,
    "complexity": 4.3,
    "best_weather": "Crisp / Autumn Chill",
    "best_temperature": "6°C–16°C",
    "tags": ["Hercules", "Liam Grey", "Chai", "Tobacco", "Cinnamon"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Neck\n• Layer 2: Liam Grey (3 sprays) - Clothes / Shirt",
    "alternatives": ["Hercules", "Liam Grey", "Luxury Cashmere"]
  },
  {
    "id": 17,
    "name": "Smoked Pineapple Leather",
    "rating": 4.5,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "SNOI (Supremacy Not Only Intense)"],
    "fragrance_count": 2,
    "profile": "Dark smoky blackcurrant fruit over saffron-leather.",
    "dominant_notes": ["Saffron", "Leather", "Blackcurrant", "Oakmoss", "Ambroxan"],
    "synergy": "SNOI's intense blackcurrant-oakmoss-saffron performance overlays perfectly with Costume National I's saffron-leather-ambroxan core, amplifying the saffron bridge note shared by both fragrances into a dramatic, layered accord.",
    "projection": 4.7,
    "longevity": 4.9,
    "compliment_factor": 4.5,
    "complexity": 4.6,
    "best_weather": "Cold / Clear Night",
    "best_temperature": "2°C–14°C",
    "tags": ["Costume National I", "SNOI", "Leather", "Blackcurrant", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Chest\n• Layer 2: SNOI (Supremacy Not Only Intense) (2 sprays) - Clothes / Leather Jacket",
    "alternatives": ["SNOI (Supremacy Not Only Intense)", "Costume National I", "Aromatic Ink & Leather"]
  },
  {
    "id": 18,
    "name": "Seductive Vanilla Leather",
    "rating": 4.8,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Spectre Ghost"],
    "fragrance_count": 2,
    "profile": "Saffron-leather sweetened by warm spiced vanilla.",
    "dominant_notes": ["Saffron", "Leather", "Vanilla", "Cardamom", "Ambroxan"],
    "synergy": "The bold, structural saffron-leather-ambroxan of Costume National I is beautifully sweetened and rounded by Spectre Ghost's vanilla-cardamom-benzoin, creating an evening fragrance of real presence and seductive complexity.",
    "projection": 4.5,
    "longevity": 4.7,
    "compliment_factor": 4.9,
    "complexity": 4.4,
    "best_weather": "Cold / Severe Cold",
    "best_temperature": "2°C–14°C",
    "tags": ["Costume National I", "Spectre Ghost", "Leather", "Vanilla", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Spectre Ghost (2 sprays) - Coat",
    "alternatives": ["Costume National I", "Spectre Ghost", "Bad Boy in a Clean Suit"]
  },
  {
    "id": 19,
    "name": "Spiced Vanilla Tobacco",
    "rating": 4.4,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Hercules", "Al Nashama Caprice"],
    "fragrance_count": 2,
    "profile": "Powdery warm cardamom-lavender over spiced tobacco.",
    "dominant_notes": ["Tobacco", "Vanilla", "Cardamom", "Lavender", "Cinnamon"],
    "synergy": "Caprice's clean cardamom and lavender top introduces an aromatic freshness directly into Hercules' dark cinnamon-tobacco base, lifting the heavy tobacco into a more complex, wearable tobacco-spice accord.",
    "projection": 4.2,
    "longevity": 4.5,
    "compliment_factor": 4.4,
    "complexity": 4.2,
    "best_weather": "Cool / Windy",
    "best_temperature": "6°C–18°C",
    "tags": ["Hercules", "Al Nashama Caprice", "Tobacco", "Lavender", "Cardamom"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Chest\n• Layer 2: Al Nashama Caprice (3 sprays) - Clothes / Shirt",
    "alternatives": ["Hercules", "Al Nashama Caprice", "Spiced Chai & Tobacco"]
  },
  {
    "id": 20,
    "name": "Salty Watermelon Tobacco",
    "rating": 4.0,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Hercules", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Experimental sweet-salty marine tobacco.",
    "dominant_notes": ["Tobacco", "Vanilla", "Sea Notes", "Violet", "Cinnamon"],
    "synergy": "A daring contrast. The salty, ozonic marine-violet of Milestone cuts through the dense cinnamon-tobacco of Hercules, creating a unique salted tobacco illusion more wearable in mild autumn temperatures than Hercules alone.",
    "projection": 4.0,
    "longevity": 4.1,
    "compliment_factor": 3.9,
    "complexity": 4.6,
    "best_weather": "Mild Autumn Day",
    "best_temperature": "12°C–20°C",
    "tags": ["Hercules", "CDNI Milestone", "Tobacco", "Sea Notes", "Cinnamon"],
    "steps": "Order 1:\n• Layer 1: Hercules (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (3 sprays) - Clothes / Shirt",
    "alternatives": ["Hercules", "CDNI Milestone", "Spiced Chai & Tobacco"]
  },
  {
    "id": 21,
    "name": "Imperial Saffron Blue",
    "rating": 4.4,
    "season": "Autumn",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Costume National I", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Exotic saffron-leather beneath radiant blue ambroxan.",
    "dominant_notes": ["Saffron", "Leather", "Grapefruit", "Ambroxan", "Lavender"],
    "synergy": "Costume National I creates a bold saffron-leather-ambroxan base that anchors and contrasts with Turathi Blue's projecting fresh grapefruit citrus, the ambroxan shared by both fragrances forming a powerful bridge.",
    "projection": 4.5,
    "longevity": 4.6,
    "compliment_factor": 4.5,
    "complexity": 4.3,
    "best_weather": "Cool / Clear",
    "best_temperature": "8°C–18°C",
    "tags": ["Costume National I", "Turathi Blue", "Saffron", "Ambroxan", "Leather"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (2 sprays) - Clothes / Shirt",
    "alternatives": ["Costume National I", "Turathi Blue", "Bad Boy in a Clean Suit"]
  },
  {
    "id": 22,
    "name": "Midnight Metallic Ocean",
    "rating": 4.1,
    "season": "Summer",
    "time_of_day": "Night",
    "occasion": "Casual",
    "fragrances": ["SNOI (Supremacy Not Only Intense)", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Dark smoky blackcurrant over fresh marine salt.",
    "dominant_notes": ["Blackcurrant", "Oakmoss", "Sea Notes", "Violet", "Saffron"],
    "synergy": "Milestone's ozonic sea-salt and violet marine character adds a surprisingly effective coastal airiness to the dense blackcurrant-oakmoss of SNOI, making the latter wearable in warmer summer nights.",
    "projection": 4.2,
    "longevity": 4.3,
    "compliment_factor": 4.2,
    "complexity": 4.0,
    "best_weather": "Warm Summer Night",
    "best_temperature": "20°C–28°C",
    "tags": ["SNOI", "CDNI Milestone", "Marine", "Blackcurrant", "Oakmoss"],
    "steps": "Order 1:\n• Layer 1: SNOI (Supremacy Not Only Intense) (2 sprays) - Skin / Neck\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Shoulders",
    "alternatives": ["SNOI (Supremacy Not Only Intense)", "CDNI Milestone", "Alpine Ocean Breeze"]
  },
  {
    "id": 23,
    "name": "Smoky Mountain Vetiver",
    "rating": 4.1,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Encre Noire l'Extreme", "Supremacy In Heaven"],
    "fragrance_count": 2,
    "profile": "Dark vetiver-incense ventilated by green tea and blackcurrant.",
    "dominant_notes": ["Vetiver", "Cypress", "Green Tea", "Blackcurrant", "Incense"],
    "synergy": "Supremacy In Heaven provides a clean, sharp blackcurrant-bergamot airiness that ventilates and lightens the oppressive dark vetiver-cypress-incense core of Encre Noire l'Extreme, making it daytime viable.",
    "projection": 4.0,
    "longevity": 4.2,
    "compliment_factor": 3.7,
    "complexity": 4.5,
    "best_weather": "Damp / Foggy",
    "best_temperature": "10°C–18°C",
    "tags": ["Encre Noire l'Extreme", "Supremacy In Heaven", "Vetiver", "Ink", "Green Tea"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Neck\n• Layer 2: Supremacy In Heaven (3 sprays) - Clothes / Shirt",
    "alternatives": ["Encre Noire l'Extreme", "Supremacy In Heaven", "Inky Citrus Bomb"]
  },
  {
    "id": 24,
    "name": "Aromatic Ink & Leather",
    "rating": 4.4,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Costume National I"],
    "fragrance_count": 2,
    "profile": "Intense dark vetiver-cypress over saffron-leather ambroxan.",
    "dominant_notes": ["Cypress", "Incense", "Saffron", "Leather", "Vetiver"],
    "synergy": "A deliberately avant-garde combination. The earthy cypress-vetiver-incense darkness of Encre Noire meets the bold saffron-leather-ambroxan of Costume National I — both niche-quality originals that clash and merge into something uniquely challenging and atmospheric.",
    "projection": 4.5,
    "longevity": 4.9,
    "compliment_factor": 3.8,
    "complexity": 4.9,
    "best_weather": "Freezing Night",
    "best_temperature": "0°C–10°C",
    "tags": ["Encre Noire l'Extreme", "Costume National I", "Cypress", "Incense", "Leather"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Costume National I (2 sprays) - Clothes / Jacket",
    "alternatives": ["Costume National I", "Encre Noire l'Extreme", "Sovereign Niche Overlord"]
  },
  {
    "id": 25,
    "name": "Citrus Saffron Spark",
    "rating": 4.1,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Costume National I", "Jean Lowe Immortal"],
    "fragrance_count": 2,
    "profile": "Saffron-leather brightened by zingy ginger-grapefruit.",
    "dominant_notes": ["Saffron", "Leather", "Ginger", "Grapefruit", "Ambroxan"],
    "synergy": "Immortal's ginger-grapefruit-ambroxan top introduces an energetic, contemporary freshness to the opening of Costume National I's bold saffron-leather, creating an unusual bridge between fresh and dark-leathery.",
    "projection": 4.3,
    "longevity": 4.5,
    "compliment_factor": 4.1,
    "complexity": 4.2,
    "best_weather": "Crisp Morning",
    "best_temperature": "10°C–20°C",
    "tags": ["Costume National I", "Jean Lowe Immortal", "Leather", "Ginger", "Saffron"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Neck\n• Layer 2: Jean Lowe Immortal (2 sprays) - Clothes / Shirt",
    "alternatives": ["Costume National I", "Jean Lowe Immortal", "Imperial Saffron Blue"]
  },
  {
    "id": 26,
    "name": "Golden Pineapple Breeze",
    "rating": 4.4,
    "season": "Spring / Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Supremacy Collector's Edition", "Divin Asylum"],
    "fragrance_count": 2,
    "profile": "Premium sharp tropical pineapple with sparkling multi-citrus.",
    "dominant_notes": ["Pineapple", "Apple", "Grapefruit", "Lime", "Oakmoss"],
    "synergy": "Divin Asylum's premium lime-lemon-grapefruit multi-citrus supercharges the fruity pineapple-apple opening of the Collector's Edition, and its vetiver base provides a sophisticated anchor missing from the Collector's Edition alone.",
    "projection": 4.3,
    "longevity": 4.2,
    "compliment_factor": 4.6,
    "complexity": 3.8,
    "best_weather": "Sunny / High Heat",
    "best_temperature": "22°C–34°C",
    "tags": ["Supremacy Collector's Edition", "Divin Asylum", "Pineapple", "Tropical", "Citrus"],
    "steps": "Order 1:\n• Layer 1: Supremacy Collector's Edition (2 sprays) - Skin / Chest\n• Layer 2: Divin Asylum (3 sprays) - Clothes / Shirt",
    "alternatives": ["Supremacy Collector's Edition", "Divin Asylum", "Emperor's Sovereign"]
  },
  {
    "id": 27,
    "name": "Emperor's Sovereign",
    "rating": 4.7,
    "season": "Spring / Autumn",
    "time_of_day": "All",
    "occasion": "Formal",
    "fragrances": ["SNOI (Supremacy Not Only Intense)", "Supremacy Collector's Edition", "Divin Asylum"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Deep multi-dimensional smoky blackcurrant-pineapple.",
    "dominant_notes": ["Blackcurrant", "Pineapple", "Lime", "Oakmoss", "Ambroxan"],
    "synergy": "SNOI's dense blackcurrant-oakmoss-saffron anchors the bottom, the Collector's Edition provides the pineapple-birch fruity mid-layer, and Divin Asylum adds niche sparkling multi-citrus projection at the top.",
    "projection": 4.6,
    "longevity": 4.7,
    "compliment_factor": 4.8,
    "complexity": 4.6,
    "best_weather": "Clear / Pleasant",
    "best_temperature": "14°C–26°C",
    "tags": ["SNOI", "Supremacy Collector's Edition", "Divin Asylum", "Blackcurrant", "Smoky"],
    "steps": "Order 1:\n• Layer 1: SNOI (Supremacy Not Only Intense) (1 spray) - Skin / Chest\n• Layer 2: Supremacy Collector's Edition (2 sprays) - Skin / Neck\n• Layer 3: Divin Asylum (2 sprays) - Clothes / Shoulders",
    "alternatives": ["SNOI (Supremacy Not Only Intense)", "Supremacy Collector's Edition", "Golden Pineapple Breeze"]
  },
  {
    "id": 28,
    "name": "Gothic Vanilla Incense",
    "rating": 4.5,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Formal / Evening",
    "fragrances": ["Encre Noire l'Extreme", "Hercules", "Spectre Ghost"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Mysterious dark vetiver, tobacco, and rich vanilla.",
    "dominant_notes": ["Vetiver", "Tobacco", "Vanilla", "Incense", "Cypress"],
    "synergy": "Encre Noire adds an inky vetiver-cypress darkness beneath Hercules' cinnamon-tobacco, while Spectre Ghost's vanilla-cardamom crowns the top with warmth, creating a three-tier dark gothic accord.",
    "projection": 4.4,
    "longevity": 4.8,
    "compliment_factor": 4.2,
    "complexity": 4.9,
    "best_weather": "Cold / Dark Overcast",
    "best_temperature": "0°C–12°C",
    "tags": ["Encre Noire l'Extreme", "Hercules", "Spectre Ghost", "Vanilla", "Incense"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: Hercules (2 sprays) - Skin / Neck\n• Layer 3: Spectre Ghost (2 sprays) - Clothes / Coat",
    "alternatives": ["Hercules", "Spectre Ghost", "Sovereign Niche Overlord"]
  },
  {
    "id": 29,
    "name": "Royal Cardamom Sea",
    "rating": 4.3,
    "season": "Spring / Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Aquatic citrus with warm cardamom-lavender spice.",
    "dominant_notes": ["Grapefruit", "Ambroxan", "Cardamom", "Lavender", "Sea Notes"],
    "synergy": "Turathi provides deep blue ambroxan-citrus weight, Caprice introduces a warm cardamom-lavender aromatic mid-tier, and Milestone adds a salty marine freshness. Best in mild temperatures — Caprice's warm spice limits summer use.",
    "projection": 4.4,
    "longevity": 4.4,
    "compliment_factor": 4.5,
    "complexity": 4.3,
    "best_weather": "Mild / Clear",
    "best_temperature": "14°C–24°C",
    "tags": ["Turathi Blue", "Al Nashama Caprice", "CDNI Milestone", "Aquatic", "Cardamom"],
    "steps": "Order 1:\n• Layer 1: Al Nashama Caprice (1 spray) - Skin / Chest\n• Layer 2: Turathi Blue (2 sprays) - Skin / Neck\n• Layer 3: CDNI Milestone (2 sprays) - Clothes / Collar",
    "alternatives": ["Turathi Blue", "Al Nashama Caprice", "High-Heat Overlord"]
  },
  {
    "id": 30,
    "name": "Ultimate Zesty Aquatic",
    "rating": 4.5,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Extreme hot weather citrus-marine-ambroxan defence.",
    "dominant_notes": ["Grapefruit", "Ambroxan", "Sea Notes", "Violet", "Ginger"],
    "synergy": "Triple citrus-ambroxan-marine layering for maximum summer projection. Turathi provides the dominant blue ambroxan, Milestone adds marine freshness, Immortal contributes ginger depth and additional ambroxan longevity.",
    "projection": 4.6,
    "longevity": 4.5,
    "compliment_factor": 4.5,
    "complexity": 3.9,
    "best_weather": "Extreme Heat",
    "best_temperature": "28°C–40°C",
    "tags": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal", "Aquatic", "Citrus"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Chest\n• Layer 2: CDNI Milestone (2 sprays) - Skin / Neck\n• Layer 3: Turathi Blue (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Turathi Blue", "CDNI Milestone", "High-Heat Overlord"]
  },
  {
    "id": 31,
    "name": "Executive Creed Tribute",
    "rating": 4.4,
    "season": "Spring",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Ash'aa Oud Noir", "Supremacy Collector's Edition", "CDNI Milestone"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Green juniper, pineapple, and marine salt-air.",
    "dominant_notes": ["Bergamot", "Violet", "Pineapple", "Sea Notes", "Juniper Berry"],
    "synergy": "A tribute to Creed's spring DNA. Ash'aa Oud Noir provides the crisp green freshness of GIT, the Collector's Edition adds the fruity pineapple of Aventus, and Milestone layers the oceanic freshness of Millésime Impérial.",
    "projection": 4.3,
    "longevity": 4.3,
    "compliment_factor": 4.4,
    "complexity": 4.2,
    "best_weather": "Bright / Sunny",
    "best_temperature": "16°C–26°C",
    "tags": ["Ash'aa Oud Noir", "Supremacy Collector's Edition", "CDNI Milestone", "Violet", "Pineapple"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: Supremacy Collector's Edition (1 spray) - Skin / Chest\n• Layer 3: CDNI Milestone (2 sprays) - Clothes / Shirt",
    "alternatives": ["Supremacy Collector's Edition", "CDNI Milestone", "Executive Fresh"]
  },
  {
    "id": 32,
    "name": "Sovereign Niche Overlord",
    "rating": 4.8,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal",
    "fragrances": ["Encre Noire l'Extreme", "Costume National I", "Liam Grey", "Spectre Ghost"],
    "fragrance_count": 4,
    "profile": "[4-LAYER] Ultimate niche symphony of vetiver, saffron-leather, fig tea, and vanilla.",
    "dominant_notes": ["Vetiver", "Leather", "Black Tea", "Vanilla", "Saffron"],
    "synergy": "A masterclass four-layer dark arrangement. Encre Noire anchors with earthy vetiver-cypress, Costume National I adds bold saffron-leather-ambroxan, Liam Grey bridges with powdery fig-tea, and Spectre Ghost crowns with warm vanilla-cardamom.",
    "projection": 4.7,
    "longevity": 4.9,
    "compliment_factor": 4.6,
    "complexity": 5.0,
    "best_weather": "Extreme Cold / Frosty",
    "best_temperature": "0°C–8°C",
    "tags": ["Encre Noire l'Extreme", "Costume National I", "Liam Grey", "Spectre Ghost", "Leather"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Lower Back\n• Layer 2: Costume National I (2 sprays) - Skin / Chest\n• Layer 3: Liam Grey (2 sprays) - Skin / Neck\n• Layer 4: Spectre Ghost (2 sprays) - Clothes / Coat",
    "alternatives": ["Encre Noire l'Extreme", "Costume National I", "Gothic Vanilla Incense"]
  },
  {
    "id": 33,
    "name": "High-Heat Overlord",
    "rating": 4.7,
    "season": "Summer",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal", "Supremacy Collector's Edition"],
    "fragrance_count": 4,
    "profile": "[4-LAYER] Ultimate summer citrus-marine-ambroxan-fruit blockbuster.",
    "dominant_notes": ["Grapefruit", "Ambroxan", "Pineapple", "Sea Notes", "Ginger"],
    "synergy": "Maximum warm-weather performance using complementary fresh and fruity layers. Immortal anchors with ambroxan, Milestone adds marine freshness, Turathi Blue projects citrus, and the Collector's Edition adds pineapple-fruit sweetness on top.",
    "projection": 4.8,
    "longevity": 4.7,
    "compliment_factor": 4.7,
    "complexity": 4.4,
    "best_weather": "Scorching Heat",
    "best_temperature": "28°C–40°C",
    "tags": ["Turathi Blue", "CDNI Milestone", "Jean Lowe Immortal", "Supremacy Collector's Edition", "Ambroxan"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Chest\n• Layer 2: CDNI Milestone (2 sprays) - Skin / Neck\n• Layer 3: Supremacy Collector's Edition (1 spray) - Skin / Wrist\n• Layer 4: Turathi Blue (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Turathi Blue", "Jean Lowe Immortal", "Ultimate Zesty Aquatic"]
  },
  {
    "id": 34,
    "name": "Smoked Fig & Tea",
    "rating": 4.6,
    "season": "Autumn",
    "time_of_day": "All",
    "occasion": "Office",
    "fragrances": ["SNOI (Supremacy Not Only Intense)", "Liam Grey"],
    "fragrance_count": 2,
    "profile": "Creamy fig-tea with a dark smoky blackcurrant-oakmoss edge.",
    "dominant_notes": ["Blackcurrant", "Fig", "Black Tea", "Oakmoss", "Saffron"],
    "synergy": "Liam Grey's creamy fig and sandalwood completely smooths out the intense blackcurrant-oakmoss of SNOI, rounding its beast-mode projection into a sophisticated niche aura with shared saffron complexity.",
    "projection": 4.4,
    "longevity": 4.7,
    "compliment_factor": 4.6,
    "complexity": 4.5,
    "best_weather": "Mild / Overcast",
    "best_temperature": "12°C–22°C",
    "tags": ["SNOI", "Liam Grey", "Fig", "Blackcurrant", "Smoky"],
    "steps": "Order 1 (Balanced):\n• Layer 1: SNOI (Supremacy Not Only Intense) (1 spray) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Neck",
    "alternatives": ["Liam Grey", "Supremacy Collector's Edition"]
  },
  {
    "id": 35,
    "name": "Sparkling Vanilla Woods",
    "rating": 4.6,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Spectre Ghost", "Turathi Blue"],
    "fragrance_count": 2,
    "profile": "Citrus-ambroxan making warm vanilla sparkle in cooler weather.",
    "dominant_notes": ["Grapefruit", "Vanilla", "Ambroxan", "Cardamom", "Ginger"],
    "synergy": "Spectre Ghost's heavy vanilla-cardamom base needs lift. Turathi Blue provides a dose of grapefruit and ambroxan projection that elevates the vanilla into a more dynamic, sparkling accord. Best in cool weather — Spectre Ghost is too heavy for warm conditions.",
    "projection": 4.4,
    "longevity": 4.7,
    "compliment_factor": 4.8,
    "complexity": 4.2,
    "best_weather": "Cool / Crisp",
    "best_temperature": "8°C–20°C",
    "tags": ["Turathi Blue", "Spectre Ghost", "Vanilla", "Grapefruit", "Ambroxan"],
    "steps": "Order 1:\n• Layer 1: Spectre Ghost (2 sprays) - Skin / Chest\n• Layer 2: Turathi Blue (3 sprays) - Clothes / Shoulders",
    "alternatives": ["Spectre Ghost", "Upscale Ginger Cream-Soda"]
  },
  {
    "id": 36,
    "name": "Gentleman's Transition",
    "rating": 4.3,
    "season": "Autumn",
    "time_of_day": "Night",
    "occasion": "Evening",
    "fragrances": ["Ash'aa Oud Noir", "Hercules"],
    "fragrance_count": 2,
    "profile": "Fresh green juniper giving way to warm cinnamon tobacco.",
    "dominant_notes": ["Tobacco", "Juniper Berry", "Cinnamon", "Violet", "Vanilla"],
    "synergy": "A journey of contrast. The precise, tailored green-juniper opening of Ash'aa Oud Noir introduces a fresh, structured feel that slowly gives way to the cosy, sweet cinnamon-tobacco of Hercules as the skin evolves.",
    "projection": 4.1,
    "longevity": 4.5,
    "compliment_factor": 4.3,
    "complexity": 4.7,
    "best_weather": "Cool / Crisp",
    "best_temperature": "8°C–18°C",
    "tags": ["Ash'aa Oud Noir", "Hercules", "Tobacco", "Green", "Contrast"],
    "steps": "Order 1:\n• Layer 1: Ash'aa Oud Noir (2 sprays) - Skin / Neck\n• Layer 2: Hercules (2 sprays) - Clothes / Chest",
    "alternatives": ["Hercules", "Spiced Chai & Tobacco"]
  },
  {
    "id": 37,
    "name": "Royal Tea & Citrus",
    "rating": 4.6,
    "season": "Spring / Autumn",
    "time_of_day": "Day",
    "occasion": "Office",
    "fragrances": ["Supremacy In Heaven", "Turathi Blue", "Liam Grey"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Multi-faceted green tea, fig, and ambroxan-citrus powerhouse.",
    "dominant_notes": ["Green Tea", "Grapefruit", "Fig", "Black Tea", "Ambroxan"],
    "synergy": "Liam Grey's dense fig-tea anchors the base, Supremacy In Heaven adds the metallic green tea and blackcurrant mid-layer, and Turathi Blue's ambroxan-grapefruit amplifies overall projection, fusing both teas into an elevated office accord.",
    "projection": 4.5,
    "longevity": 4.6,
    "compliment_factor": 4.7,
    "complexity": 4.7,
    "best_weather": "Mild / Sunny",
    "best_temperature": "14°C–24°C",
    "tags": ["Supremacy In Heaven", "Turathi Blue", "Liam Grey", "Tea", "Fig"],
    "steps": "Order 1:\n• Layer 1: Liam Grey (2 sprays) - Skin / Chest\n• Layer 2: Supremacy In Heaven (2 sprays) - Skin / Neck\n• Layer 3: Turathi Blue (2 sprays) - Clothes / Shoulders",
    "alternatives": ["Emperor's Tea Accord", "Turathi Blue"]
  },
  {
    "id": 38,
    "name": "The Elysian Ghost",
    "rating": 4.7,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Formal / Evening",
    "fragrances": ["Spectre Ghost", "Divin Asylum", "Jean Lowe Immortal"],
    "fragrance_count": 3,
    "profile": "[3-LAYER] Ginger-vanilla gourmand lifted by premium multi-citrus.",
    "dominant_notes": ["Vanilla", "Ginger", "Lime", "Grapefruit", "Ambroxan"],
    "synergy": "Immortal acts as the bridge — its ginger top note connects with Spectre Ghost's cardamom-vanilla, while its grapefruit-ambroxan blends into Divin Asylum's premium citrus core. Best reserved for cool evenings where Spectre Ghost's heavy vanilla can bloom.",
    "projection": 4.5,
    "longevity": 4.7,
    "compliment_factor": 4.8,
    "complexity": 4.7,
    "best_weather": "Cool / Clear",
    "best_temperature": "8°C–20°C",
    "tags": ["Divin Asylum", "Spectre Ghost", "Jean Lowe Immortal", "Ginger", "Vanilla"],
    "steps": "Order 1:\n• Layer 1: Spectre Ghost (1 spray) - Skin / Chest\n• Layer 2: Jean Lowe Immortal (2 sprays) - Skin / Neck\n• Layer 3: Divin Asylum (3 sprays) - Clothes / Shirt",
    "alternatives": ["Spectre Ghost", "Upscale Ginger Cream-Soda"]
  },
  {
    "id": 39,
    "name": "Dark Moss & Leather",
    "rating": 4.5,
    "season": "Winter",
    "time_of_day": "Night",
    "occasion": "Formal / Evening",
    "fragrances": ["SNOI (Supremacy Not Only Intense)", "Costume National I"],
    "fragrance_count": 2,
    "profile": "Fruity blackcurrant-oakmoss fused with bold saffron-leather ambroxan.",
    "dominant_notes": ["Blackcurrant", "Saffron", "Leather", "Oakmoss", "Ambroxan"],
    "synergy": "SNOI's blackcurrant-oakmoss-saffron fruity-dark character fuses powerfully with Costume National I's saffron-leather-ambroxan. The saffron note is shared by both fragrances, making the bridge seamless and the overall accord deeply complex.",
    "projection": 4.8,
    "longevity": 4.9,
    "compliment_factor": 4.6,
    "complexity": 4.7,
    "best_weather": "Cold / Clear",
    "best_temperature": "0°C–12°C",
    "tags": ["SNOI", "Costume National I", "Saffron", "Leather", "Blackcurrant"],
    "steps": "Order 1:\n• Layer 1: Costume National I (2 sprays) - Skin / Chest\n• Layer 2: SNOI (Supremacy Not Only Intense) (2 sprays) - Skin / Neck",
    "alternatives": ["Smoked Pineapple Leather", "Aromatic Ink & Leather", "Sovereign Niche Overlord"]
  },
  {
    "id": 40,
    "name": "Liam & Ghost Winter Accord",
    "rating": 4.6,
    "season": "Autumn / Winter",
    "time_of_day": "Night",
    "occasion": "Casual / Evening",
    "fragrances": ["Liam Grey", "Spectre Ghost"],
    "fragrance_count": 2,
    "profile": "Milky fig-tea cushioning a spiced vanilla gourmand.",
    "dominant_notes": ["Vanilla", "Fig", "Black Tea", "Cardamom", "Sandalwood"],
    "synergy": "Both fragrances share creamy, powdery, and comforting DNA. Liam Grey's fig-tea-sandalwood provides a sophisticated, smooth base on which Spectre Ghost's warm cardamom-vanilla-ginger builds, creating a deeply cosy, wearable gourmand accord.",
    "projection": 4.0,
    "longevity": 4.7,
    "compliment_factor": 4.7,
    "complexity": 4.4,
    "best_weather": "Cold / Still",
    "best_temperature": "2°C–16°C",
    "tags": ["Liam Grey", "Spectre Ghost", "Vanilla", "Fig", "Cardamom"],
    "steps": "Order 1:\n• Layer 1: Spectre Ghost (2 sprays) - Skin / Chest\n• Layer 2: Liam Grey (3 sprays) - Clothes / Sweater",
    "alternatives": ["Spiced Chai & Tobacco", "Freezing Powerhouse", "Upscale Ginger Cream-Soda"]
  },
  {
    "id": 41,
    "name": "Coastal Executive",
    "rating": 4.3,
    "season": "Spring / Summer",
    "time_of_day": "Day",
    "occasion": "Office / Casual",
    "fragrances": ["Jean Lowe Immortal", "CDNI Milestone"],
    "fragrance_count": 2,
    "profile": "Ginger-ambroxan aromatic grounded by marine salt and violet.",
    "dominant_notes": ["Ginger", "Grapefruit", "Sea Notes", "Violet", "Ambroxan"],
    "synergy": "Jean Lowe Immortal's ginger-grapefruit-ambroxan aromatic character pairs naturally with CDNI Milestone's salty marine-violet freshness, both sharing warm-weather credentials and ambroxan-heavy bases for synergistic longevity.",
    "projection": 4.2,
    "longevity": 4.4,
    "compliment_factor": 4.3,
    "complexity": 3.9,
    "best_weather": "Warm / Sea Breeze",
    "best_temperature": "22°C–34°C",
    "tags": ["Jean Lowe Immortal", "CDNI Milestone", "Marine", "Ginger", "Ambroxan"],
    "steps": "Order 1:\n• Layer 1: Jean Lowe Immortal (2 sprays) - Skin / Chest\n• Layer 2: CDNI Milestone (2 sprays) - Clothes / Shirt",
    "alternatives": ["Alpine Ocean Breeze", "Ultimate Zesty Aquatic", "High-Heat Shield"]
  },
  {
    "id": 42,
    "name": "Autumn Ink & Pineapple",
    "rating": 4.2,
    "season": "Autumn",
    "time_of_day": "Day",
    "occasion": "Casual",
    "fragrances": ["SNOI (Supremacy Not Only Intense)", "Encre Noire l'Extreme"],
    "fragrance_count": 2,
    "profile": "Experimental fruity-blackcurrant over dark vetiver-incense.",
    "dominant_notes": ["Blackcurrant", "Oakmoss", "Vetiver", "Cypress", "Saffron"],
    "synergy": "An unconventional pairing — SNOI's fruity blackcurrant-saffron-oakmoss adds unexpected sweetness and colour to the austere vetiver-cypress darkness of Encre Noire l'Extreme, softening its polarising character while the shared earthy DNA keeps it coherent.",
    "projection": 4.2,
    "longevity": 4.5,
    "compliment_factor": 3.9,
    "complexity": 4.7,
    "best_weather": "Overcast / Damp",
    "best_temperature": "10°C–18°C",
    "tags": ["SNOI", "Encre Noire l'Extreme", "Blackcurrant", "Vetiver", "Dark"],
    "steps": "Order 1:\n• Layer 1: Encre Noire l'Extreme (1 spray) - Skin / Chest\n• Layer 2: SNOI (Supremacy Not Only Intense) (2 sprays) - Clothes / Jacket",
    "alternatives": ["Inky Citrus Bomb", "Smoky Mountain Vetiver", "Aromatic Ink & Leather"]
  }
];
