export const individualFragrances = [
  {
    "id": 1,
    "name": "SNOI (Supremacy Not Only Intense)",
    "rating": 4.6,
    "inspiration": "Aventus × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Blackcurrant", "Bergamot", "Oakmoss", "Ambergris", "Saffron"],
    "projection": 4.7,
    "longevity": 4.8,
    "versatility": 4.3,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.4,
    "night_score": 4.7,
    "office_score": 4.0,
    "casual_score": 4.4,
    "evening_score": 4.8,
    "formal_score": 4.3,
    "best_temperature": "5°C–25°C",
    "related_fragrances": ["Supremacy Collector's Edition", "Divin Asylum", "Costume National I"],
    "description": "A powerhouse Extrait de Parfum from Afnan with beast-mode performance. Opens with a rich, smoky blackcurrant and bergamot blast that leans heavily towards the dark oakmoss and saffron drydown — sitting closer to Hacivat in character than Aventus. Reviewers consistently note it outlasts almost everything in this DNA family. Four-season versatility though it truly excels in cooler weather evenings and formal settings."
  },
  {
    "id": 2,
    "name": "Supremacy Collector's Edition",
    "rating": 4.5,
    "inspiration": "Aventus Absolu × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Pineapple", "Apple", "Bergamot", "Birch", "Oakmoss"],
    "projection": 4.2,
    "longevity": 4.3,
    "versatility": 4.6,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.5,
    "night_score": 4.4,
    "office_score": 4.4,
    "casual_score": 4.6,
    "evening_score": 4.5,
    "formal_score": 4.2,
    "best_temperature": "10°C–28°C",
    "related_fragrances": ["SNOI", "Divin Asylum", "Al Nashama Caprice"],
    "description": "A fresh, modernised Aventus-DNA fragrance from Afnan that removes the smokiness of SNOI and adds a crisp apple note alongside pineapple and white florals. Reviewers describe it as the most wearable iteration of the Supremacy line — equally at home in jeans and a t-shirt as it is in the office. Excellent performance for the warm-weather months with enough mossy base to carry into autumn."
  },
  {
    "id": 3,
    "name": "Supremacy In Heaven",
    "rating": 4.0,
    "inspiration": "Silver Mountain Water",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Bergamot", "Mandarin", "Green Tea", "Blackcurrant", "Sandalwood"],
    "projection": 3.8,
    "longevity": 3.8,
    "versatility": 4.1,
    "compliment_factor": 4.0,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Office", "Casual"],
    "day_score": 4.4,
    "night_score": 3.4,
    "office_score": 4.3,
    "casual_score": 4.2,
    "evening_score": 3.5,
    "formal_score": 3.6,
    "best_temperature": "20°C–32°C",
    "related_fragrances": ["CDNI Milestone", "Liam Grey", "Encre Noire l'Extreme"],
    "description": "Afnan's clean and airy take on the Silver Mountain Water DNA. Less metallic than the original, with a prominent blackcurrant and bergamot opening over a soft green tea and woody musky base. A summer and spring daytime staple — reviewers call it an ideal office or casual fragrance when you want something effortlessly fresh without demanding attention. Performance is moderate; longevity ranges 6–8 hours with lighter projection than the rest of the Supremacy line."
  },
  {
    "id": 4,
    "name": "Turathi Blue",
    "rating": 4.6,
    "inspiration": "Tygar",
    "clone_type": "Clone",
    "fragrance_family": "Aromatic Aquatic",
    "dominant_notes": ["Grapefruit", "Citruses", "Amber", "Woody Notes", "Spicy Notes"],
    "projection": 4.4,
    "longevity": 4.5,
    "versatility": 4.7,
    "compliment_factor": 4.8,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening"],
    "day_score": 4.8,
    "night_score": 4.2,
    "office_score": 4.5,
    "casual_score": 4.7,
    "evening_score": 4.3,
    "formal_score": 3.9,
    "best_temperature": "18°C–34°C",
    "related_fragrances": ["Jean Lowe Immortal", "Al Nashama Caprice", "CDNI Milestone"],
    "description": "Afnan's Tygar-inspired citrus powerhouse — a sharper, slightly spicier take on the grapefruit-ambroxan profile that reviewers describe as a mix of Tygar and Bleu de Chanel. Opens with a fresh citrus blast that dries down into a warm, woody-amber base. Strong projection for the first 2–3 hours; longevity of 8+ hours reported across most reviews. Excellent versatility — one reviewer wears it March through November across office, dates, gym and outdoor use."
  },
  {
    "id": 5,
    "name": "Al Nashama Caprice",
    "rating": 4.5,
    "inspiration": "Bleu Électrique",
    "clone_type": "Clone",
    "fragrance_family": "Woody Spicy",
    "dominant_notes": ["Cardamom", "Lavender", "Ginger", "Bergamot", "Cedarwood"],
    "projection": 4.2,
    "longevity": 4.4,
    "versatility": 4.6,
    "compliment_factor": 4.8,
    "seasons": ["Spring", "Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.2,
    "night_score": 4.7,
    "office_score": 4.3,
    "casual_score": 4.6,
    "evening_score": 4.8,
    "formal_score": 4.3,
    "best_temperature": "8°C–22°C",
    "related_fragrances": ["Turathi Blue", "Costume National I", "Hercules"],
    "description": "Lattafa's take on the YSL La Nuit de L'Homme Bleu Électrique DNA — a cardamom-forward aromatic-spicy fragrance with fresh lavender and a warm woody amber base. Reviewers note it captures about 85% of the original, with a slightly denser, more Middle Eastern-inflected drydown. Longevity of 6–8 hours with moderate projection. Stands out as a versatile all-year-round choice at a conservative dose; excels in autumn and winter evenings where the cardamom warmth truly blooms."
  },
  {
    "id": 6,
    "name": "Jean Lowe Immortal",
    "rating": 4.5,
    "inspiration": "L'Immensité",
    "clone_type": "Clone",
    "fragrance_family": "Woody Aromatic",
    "dominant_notes": ["Ginger", "Grapefruit", "Bergamot", "Rosemary", "Ambroxan"],
    "projection": 4.2,
    "longevity": 4.4,
    "versatility": 4.6,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Office", "Casual", "Evening"],
    "day_score": 4.7,
    "night_score": 4.0,
    "office_score": 4.5,
    "casual_score": 4.6,
    "evening_score": 4.2,
    "formal_score": 4.0,
    "best_temperature": "18°C–30°C",
    "related_fragrances": ["Turathi Blue", "Divin Asylum", "Spectre Ghost"],
    "description": "Maison Alhambra's faithful rendering of LV L'Immensité. Opens with a clean, zingy ginger-grapefruit burst that reviewers describe as almost identical to the original once it settles past a slightly synthetic opening. Rosemary and water notes form the aromatic heart before a smooth ambroxan base takes over. Longevity of 8 hours with strong projection for the first 2–3 hours. A reliable warm-weather daytime fragrance particularly praised as a compliment-getter at the office and on casual outings."
  },
  {
    "id": 7,
    "name": "Divin Asylum",
    "rating": 4.4,
    "inspiration": "Elysium Parfum Cologne",
    "clone_type": "Clone",
    "fragrance_family": "Citrus Aromatic",
    "dominant_notes": ["Grapefruit", "Lime", "Lemon", "Vetiver", "Blackcurrant"],
    "projection": 3.8,
    "longevity": 3.8,
    "versatility": 4.5,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Formal", "Evening"],
    "day_score": 4.7,
    "night_score": 4.0,
    "office_score": 4.4,
    "casual_score": 4.6,
    "evening_score": 4.1,
    "formal_score": 4.1,
    "best_temperature": "16°C–28°C",
    "related_fragrances": ["Jean Lowe Immortal", "Liam Grey", "Supremacy Collector's Edition"],
    "description": "Fragrance World's Roja Elysium clone with a full citrus-to-vetiver pyramid. Reviewers call it 95% identical to the original in scent quality and character, though performance is the notable caveat — projection and longevity have declined in recent batches, mirroring the original. The vibrant multi-citrus opening of grapefruit, lime and lemon over a clean vetiver-leather base delivers exceptional versatility across three seasons. Best enjoyed with conservative application to counter its moderate sillage."
  },
  {
    "id": 8,
    "name": "CDNI Milestone",
    "rating": 4.2,
    "inspiration": "Millésime Impérial",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Sea Notes", "Red Fruits", "Bergamot", "Violet", "Ambroxan"],
    "projection": 4.0,
    "longevity": 4.3,
    "versatility": 4.3,
    "compliment_factor": 4.3,
    "seasons": ["Spring", "Summer"],
    "time_of_day": ["Day"],
    "occasion": ["Casual", "Office"],
    "day_score": 4.6,
    "night_score": 3.7,
    "office_score": 4.2,
    "casual_score": 4.5,
    "evening_score": 3.8,
    "formal_score": 3.6,
    "best_temperature": "22°C–34°C",
    "related_fragrances": ["Supremacy In Heaven", "Turathi Blue", "SNOI"],
    "description": "Armaf's 90–95% match to Creed Millésime Impérial at a fraction of the price. Opens with a salty, sweet-melon and sea-note accord before a violet-dominant heart gives way to a heavy ambroxan-musk drydown. Reviewers praise its superior longevity versus the original (7–8+ hours). The violet note is more pronounced than in MI, lending a slightly heavier and more masculine character. A pure warm-weather fragrance — outstanding for spring and summer coastal, office and casual use. Completely unisex."
  },
  {
    "id": 9,
    "name": "Ash'aa Oud Noir",
    "rating": 4.3,
    "inspiration": "Green Irish Tweed",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Bergamot", "Juniper Berry", "Violet", "Geranium", "Sandalwood"],
    "projection": 3.9,
    "longevity": 4.2,
    "versatility": 4.3,
    "compliment_factor": 4.2,
    "seasons": ["Spring", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Office", "Formal", "Casual"],
    "day_score": 4.5,
    "night_score": 3.7,
    "office_score": 4.5,
    "casual_score": 4.1,
    "evening_score": 3.8,
    "formal_score": 4.3,
    "best_temperature": "12°C–24°C",
    "related_fragrances": ["Jean Lowe Immortal", "Divin Asylum", "Supremacy Collector's Edition"],
    "description": "Arabiyat Prestige's Green Irish Tweed clone, widely regarded as one of the better GIT dupes available. Reviewers describe it as capturing the fresh cut-grass, violet leaf and slightly ozonic character of the original with high accuracy — one reviewer found it side-by-side indistinguishable from GIT in the drydown. Opens with bergamot and juniper berry, settling into a clean violet-geranium heart over a warm cedarwood-amber base. A spring and autumn fragrance best suited for cooler daytime wear."
  },
  {
    "id": 10,
    "name": "Liam Grey",
    "rating": 4.4,
    "inspiration": "Gris Charnel",
    "clone_type": "Clone",
    "fragrance_family": "Amber Spicy",
    "dominant_notes": ["Fig", "Black Tea", "Cardamom", "Iris", "Sandalwood"],
    "projection": 4.0,
    "longevity": 4.5,
    "versatility": 4.5,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter", "Spring"],
    "time_of_day": ["All"],
    "occasion": ["Office", "Evening", "Formal", "Casual"],
    "day_score": 4.2,
    "night_score": 4.5,
    "office_score": 4.4,
    "casual_score": 4.4,
    "evening_score": 4.6,
    "formal_score": 4.3,
    "best_temperature": "8°C–20°C",
    "related_fragrances": ["Divin Asylum", "Supremacy In Heaven", "Encre Noire l'Extreme", "Hercules"],
    "description": "Lattafa's interpretation of BDK Gris Charnel — a creamy, cardamom-led fragrance with fig, black tea and iris over a smooth sandalwood and tonka base. Reviewers describe it as one of the most refined, affordable fragrances Lattafa has released, praising how the fig and cardamom interplay with a prominent, electrifying iris note. A genuinely smooth and gender-neutral cooler-months fragrance that performs across casual, office and evening contexts with excellent longevity."
  },
  {
    "id": 11,
    "name": "Spectre Ghost",
    "rating": 4.6,
    "inspiration": "Ani",
    "clone_type": "Clone",
    "fragrance_family": "Amber Floral",
    "dominant_notes": ["Vanilla", "Ginger", "Bergamot", "Cardamom", "Pink Pepper"],
    "projection": 4.2,
    "longevity": 4.4,
    "versatility": 4.1,
    "compliment_factor": 4.9,
    "seasons": ["Autumn", "Winter", "Spring"],
    "time_of_day": ["Night"],
    "occasion": ["Evening", "Formal", "Casual"],
    "day_score": 3.7,
    "night_score": 4.8,
    "office_score": 3.4,
    "casual_score": 4.2,
    "evening_score": 4.9,
    "formal_score": 4.5,
    "best_temperature": "8°C–20°C",
    "related_fragrances": ["Jean Lowe Immortal", "Hercules", "Costume National I"],
    "description": "French Avenue's Nishane Ani clone — a warm, spicy-gourmand fragrance that reviewers confirm is a near-1:1 match to the original in the drydown. Opens with ginger, bergamot and cardamom before settling into a rich rose and pink pepper heart, ultimately landing on a creamy vanilla-patchouli base. Performance varies significantly by batch and skin chemistry — some report 11+ hours, others find it fleeting. Projection is moderate; at its best a deeply seductive evening fragrance and a prolific compliment-getter."
  },
  {
    "id": 12,
    "name": "Hercules",
    "rating": 4.3,
    "inspiration": "Herod",
    "clone_type": "Clone",
    "fragrance_family": "Amber Woody",
    "dominant_notes": ["Tobacco", "Vanilla", "Cinnamon", "Osmanthus", "Incense"],
    "projection": 4.0,
    "longevity": 4.2,
    "versatility": 3.8,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter"],
    "time_of_day": ["Night"],
    "occasion": ["Evening", "Formal", "Casual"],
    "day_score": 3.4,
    "night_score": 4.7,
    "office_score": 3.1,
    "casual_score": 4.1,
    "evening_score": 4.7,
    "formal_score": 4.4,
    "best_temperature": "2°C–16°C",
    "related_fragrances": ["Spectre Ghost", "Liam Grey", "Al Nashama Caprice"],
    "description": "Maison Alhambra's Herod clone with a more pronounced cherry-tobacco character than current PdM reformulations. Reviewers describe it as capturing the rich, sweet tobacco and vanilla core beautifully, with cinnamon-pepper spice and incense depth. One reviewer found it comparable to how earlier Herod batches behaved. Longevity is on the lower-to-moderate end (reviewers note it's not as long-lasting as hoped) and sillage stays closer to the skin — but the scent quality at $20 is considered an exceptional value."
  },
  {
    "id": 13,
    "name": "Encre Noire l'Extreme",
    "rating": 3.8,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Woody Aromatic",
    "dominant_notes": ["Vetiver", "Cypress", "Elemi", "Incense", "Orris Root"],
    "projection": 4.1,
    "longevity": 4.4,
    "versatility": 3.2,
    "compliment_factor": 3.5,
    "seasons": ["Autumn", "Winter"],
    "time_of_day": ["Night"],
    "occasion": ["Formal", "Evening", "Office"],
    "day_score": 3.6,
    "night_score": 4.3,
    "office_score": 3.7,
    "casual_score": 3.4,
    "evening_score": 4.2,
    "formal_score": 4.3,
    "best_temperature": "5°C–18°C",
    "related_fragrances": ["Turathi Blue", "Liam Grey", "Costume National I", "Supremacy In Heaven"],
    "description": "The EDP flanker to the iconic Lalique Encre Noire, layering the original's dark vetiver-cypress DNA with balsamic elemi resin and smouldering incense for a richer, more brooding character. A deliberate avant-garde fragrance — polarising and not for the sweet-fragrance crowd. Reviewers describe it as evoking damp autumn forests and gothic elegance. Firmly a cold-weather evening and formal fragrance; its complex darkness is a feature for the right wearer."
  },
  {
    "id": 14,
    "name": "Costume National I",
    "rating": 4.4,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Oriental Spicy",
    "dominant_notes": ["Cardamom", "Cinnamon", "Cloves", "Sandalwood", "Labdanum"],
    "projection": 4.6,
    "longevity": 4.8,
    "versatility": 3.9,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter"],
    "time_of_day": ["Night"],
    "occasion": ["Evening", "Formal", "Casual"],
    "day_score": 3.5,
    "night_score": 4.7,
    "office_score": 3.6,
    "casual_score": 3.8,
    "evening_score": 4.8,
    "formal_score": 4.6,
    "best_temperature": "5°C–18°C",
    "related_fragrances": ["Al Nashama Caprice", "SNOI", "Spectre Ghost", "Encre Noire l'Extreme"],
    "description": "The Costume National Homme EDP — an Italian avant-garde creation by Dominique Ropion combining a brief sparkling grapefruit-cardamom opening with a dense heart of cinnamon, cloves and thyme, all anchored by smooth sandalwood and labdanum. Reviewers praise its extraordinary performance (16 hours cited), its metropolitan character and how the spice never becomes cloying thanks to the sandalwood's smoothing effect. A strictly cool-weather evening fragrance — brilliant for winter formal occasions, dinner dates and after-dark settings."
  }
];
