export const individualFragrances = [
  {
    "id": 1,
    "name": "SNOI (Supremacy Not Only Intense)",
    "rating": 4.6,
    "inspiration": "Aventus × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Pineapple", "Blackcurrant", "Oakmoss", "Ambergris"],
    "projection": 4.7,
    "longevity": 4.8,
    "versatility": 4.2,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn"],
    "day_score": 4.5,
    "night_score": 4.6,
    "office_score": 3.8,
    "casual_score": 4.5,
    "evening_score": 4.7,
    "formal_score": 4.2,
    "best_temperature": "22°C",
    "related_fragrances": ["Supremacy Collector's Edition", "Divin Asylum", "Costume National I"],
    "description": "A powerful and intense fruit-forward opening backed by a heavy, smoky oakmoss base. Renowned for its beast-mode performance."
  },
  {
    "id": 2,
    "name": "Supremacy Collector's Edition",
    "rating": 4.5,
    "inspiration": "Aventus Absolu × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Pineapple", "Grapefruit", "Ginger", "Oakmoss"],
    "projection": 4.4,
    "longevity": 4.5,
    "versatility": 4.3,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Summer", "Autumn"],
    "day_score": 4.4,
    "night_score": 4.5,
    "office_score": 4.0,
    "casual_score": 4.5,
    "evening_score": 4.6,
    "formal_score": 4.3,
    "best_temperature": "20°C",
    "related_fragrances": ["SNOI", "Divin Asylum", "Al Nashama Caprice"],
    "description": "A premium take on the rich fruity-smoky DNA, blending the sophisticated fruitiness of Aventus Absolu with the earthy backbone of Hacivat."
  },
  {
    "id": 3,
    "name": "Supremacy In Heaven",
    "rating": 4.0,
    "inspiration": "Silver Mountain Water",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Green Tea", "Blackcurrant", "Bergamot", "Sandalwood"],
    "projection": 3.9,
    "longevity": 4.0,
    "versatility": 4.1,
    "compliment_factor": 4.1,
    "seasons": ["Spring", "Summer"],
    "day_score": 4.5,
    "night_score": 3.5,
    "office_score": 4.4,
    "casual_score": 4.2,
    "evening_score": 3.6,
    "formal_score": 3.8,
    "best_temperature": "25°C",
    "related_fragrances": ["CDNI Milestone", "Liam Grey", "Encre Noire l'Extreme"],
    "description": "A crisp, metallic, and exceptionally clean scent capturing pristine alpine air, fresh green tea, and smooth blackcurrant edges."
  },
  {
    "id": 4,
    "name": "Turathi Blue",
    "rating": 4.6,
    "inspiration": "Tygar",
    "clone_type": "Clone",
    "fragrance_family": "Citrus Aromatic",
    "dominant_notes": ["Grapefruit", "Ambroxan", "Woody Notes", "Musk"],
    "projection": 4.5,
    "longevity": 4.6,
    "versatility": 4.6,
    "compliment_factor": 4.8,
    "seasons": ["Spring", "Summer"],
    "day_score": 4.8,
    "night_score": 4.2,
    "office_score": 4.5,
    "casual_score": 4.7,
    "evening_score": 4.3,
    "formal_score": 4.0,
    "best_temperature": "28°C",
    "related_fragrances": ["Jean Lowe Immortal", "Al Nashama Caprice", "CDNI Milestone"],
    "description": "An effervescent, sparkling grapefruit opening over a heavy, radiating bed of warm ambergris-like ambroxan and modern linear woods."
  },
  {
    "id": 5,
    "name": "Al Nashama Caprice",
    "rating": 4.5,
    "inspiration": "Bleu Électrique",
    "clone_type": "Clone",
    "fragrance_family": "Woody Spicy",
    "dominant_notes": ["Cardamom", "Lavender", "Ginger", "Cedarwood"],
    "projection": 4.3,
    "longevity": 4.5,
    "versatility": 4.5,
    "compliment_factor": 4.8,
    "seasons": ["Spring", "Autumn", "Winter"],
    "day_score": 4.0,
    "night_score": 4.8,
    "office_score": 4.2,
    "casual_score": 4.5,
    "evening_score": 4.8,
    "formal_score": 4.4,
    "best_temperature": "18°C",
    "related_fragrances": ["Turathi Blue", "Costume National I", "Hercules"],
    "description": "A seductive, powdery lavender and fresh spicy cardamom fragrance. Excellent for dates, crisp evenings, or signature daily use."
  },
  {
    "id": 6,
    "name": "Jean Lowe Immortal",
    "rating": 4.5,
    "inspiration": "L'Immensité",
    "clone_type": "Clone",
    "fragrance_family": "Amber Spicy",
    "dominant_notes": ["Ginger", "Grapefruit", "Ambroxan", "Watery Notes"],
    "projection": 4.2,
    "longevity": 4.5,
    "versatility": 4.7,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer"],
    "day_score": 4.7,
    "night_score": 4.1,
    "office_score": 4.6,
    "casual_score": 4.6,
    "evening_score": 4.2,
    "formal_score": 4.1,
    "best_temperature": "26°C",
    "related_fragrances": ["Turathi Blue", "Divin Asylum", "Spectre Ghost"],
    "description": "Bright, zesty ginger and grapefruit combined with crisp aquatic undertones and a highly radiant amber-ambroxan base."
  },
  {
    "id": 7,
    "name": "Divin Asylum",
    "rating": 4.4,
    "inspiration": "Elysium Parfum Cologne",
    "clone_type": "Clone",
    "fragrance_family": "Citrus Aromatic",
    "dominant_notes": ["Lime", "Grapefruit", "Vetiver", "Blackcurrant", "Ambergris"],
    "projection": 4.1,
    "longevity": 4.2,
    "versatility": 4.5,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Summer"],
    "day_score": 4.8,
    "night_score": 3.9,
    "office_score": 4.5,
    "casual_score": 4.7,
    "evening_score": 4.1,
    "formal_score": 4.2,
    "best_temperature": "24°C",
    "related_fragrances": ["Jean Lowe Immortal", "Liam Grey", "Supremacy Collector's Edition"],
    "description": "An ultra-premium feeling, complex citrus explosion featuring crisp lime, vetiver, and sparkling fruits with a sophisticated niche finish."
  },
  {
    "id": 8,
    "name": "CDNI Milestone",
    "rating": 4.2,
    "inspiration": "Millésime Impérial",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Sea Salt", "Melon", "Marine Notes", "White Woods"],
    "projection": 4.1,
    "longevity": 4.2,
    "versatility": 4.2,
    "compliment_factor": 4.3,
    "seasons": ["Summer"],
    "day_score": 4.6,
    "night_score": 3.8,
    "office_score": 4.1,
    "casual_score": 4.5,
    "evening_score": 3.9,
    "formal_score": 3.7,
    "best_temperature": "30°C",
    "related_fragrances": ["Supremacy In Heaven", "Turathi Blue", "SNOI"],
    "description": "A refreshing marine profile defined by crisp ocean breezes, crystallization of sea salt, and a subtle sweet melon undertone."
  },
  {
    "id": 9,
    "name": "Ash'aa Oud Noir",
    "rating": 4.3,
    "inspiration": "Green Irish Tweed",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Verbena", "Violet Leaf", "Iris", "Sandalwood"],
    "projection": 4.1,
    "longevity": 4.4,
    "versatility": 4.3,
    "compliment_factor": 4.2,
    "seasons": ["Spring", "Autumn"],
    "day_score": 4.5,
    "night_score": 3.8,
    "office_score": 4.6,
    "casual_score": 4.1,
    "evening_score": 3.9,
    "formal_score": 4.4,
    "best_temperature": "18°C",
    "related_fragrances": ["Jean Lowe Immortal", "Divin Asylum", "Supremacy Collector's Edition"],
    "description": "A sophisticated, gentlemanly green classic opening with sharp lemon verbena and powdery violet leaves over an elegant wood foundation."
  },
  {
    "id": 10,
    "name": "Liam Grey",
    "rating": 4.4,
    "inspiration": "Gris Charnel",
    "clone_type": "Clone",
    "fragrance_family": "Amber Spicy",
    "dominant_notes": ["Fig", "Black Tea", "Cardamom", "Sandalwood", "Iris"],
    "projection": 4.1,
    "longevity": 4.5,
    "versatility": 4.4,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter", "Spring"],
    "day_score": 4.2,
    "night_score": 4.5,
    "office_score": 4.5,
    "casual_score": 4.3,
    "evening_score": 4.5,
    "formal_score": 4.4,
    "best_temperature": "14°C",
    "related_fragrances": ["Divin Asylum", "Supremacy In Heaven", "Encre Noire l'Extreme", "Hercules"],
    "description": "A creamy, comforting, and highly sophisticated blend of milky fig, dark black tea, and smooth sandalwood with a powdery iris drape."
  },
  {
    "id": 11,
    "name": "Spectre Ghost",
    "rating": 4.6,
    "inspiration": "Ani",
    "clone_type": "Clone",
    "fragrance_family": "Amber Floral",
    "dominant_notes": ["Vanilla", "Ginger", "Bergamot", "Benzoin", "Cardamom"],
    "projection": 4.5,
    "longevity": 4.8,
    "versatility": 4.0,
    "compliment_factor": 4.9,
    "seasons": ["Autumn", "Winter"],
    "day_score": 3.8,
    "night_score": 4.8,
    "office_score": 3.5,
    "casual_score": 4.2,
    "evening_score": 4.9,
    "formal_score": 4.6,
    "best_temperature": "10°C",
    "related_fragrances": ["Jean Lowe Immortal", "Hercules", "Costume National I"],
    "description": "A brilliant ginger-vanilla signature gourmand. Combines an airy, bright green opening with a dense, rich woody vanilla base."
  },
  {
    "id": 12,
    "name": "Hercules",
    "rating": 4.3,
    "inspiration": "Herod",
    "clone_type": "Clone",
    "fragrance_family": "Amber Woody",
    "dominant_notes": ["Tobacco", "Vanilla", "Cinnamon", "Incense", "Labdanum"],
    "projection": 4.2,
    "longevity": 4.6,
    "versatility": 3.8,
    "compliment_factor": 4.6,
    "seasons": ["Autumn", "Winter"],
    "day_score": 3.5,
    "night_score": 4.7,
    "office_score": 3.2,
    "casual_score": 4.2,
    "evening_score": 4.7,
    "formal_score": 4.5,
    "best_temperature": "8°C",
    "related_fragrances": ["Spectre Ghost", "Liam Grey", "Al Nashama Caprice"],
    "description": "A warm, deeply comforting blend of sweet cured tobacco leaves, rich vanilla pod extracts, and prominent cinnamon bakery spices."
  },
  {
    "id": 13,
    "name": "Encre Noire l'Extreme",
    "rating": 3.8,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Woody Chypre",
    "dominant_notes": ["Vetiver", "Cypress", "Incense", "Resins", "Orris Root"],
    "projection": 4.1,
    "longevity": 4.4,
    "versatility": 3.2,
    "compliment_factor": 3.5,
    "seasons": ["Autumn", "Winter"],
    "day_score": 3.8,
    "night_score": 4.2,
    "office_score": 3.7,
    "casual_score": 3.5,
    "evening_score": 4.0,
    "formal_score": 4.3,
    "best_temperature": "12°C",
    "related_fragrances": ["Turathi Blue", "Liam Grey", "Costume National I", "Supremacy In Heaven"],
    "description": "An artistic, moody, and deep avant-garde fragrance. Blends rich, earthy vetiver configurations with damp cypress, dark incense, and heavy resins."
  },
  {
    "id": 14,
    "name": "Costume National I",
    "rating": 4.4,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Amber Spicy",
    "dominant_notes": ["Saffron", "Leather", "Amber", "Thyme", "Labdanum"],
    "projection": 4.6,
    "longevity": 4.8,
    "versatility": 3.7,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter"],
    "day_score": 3.5,
    "night_score": 4.7,
    "office_score": 3.5,
    "casual_score": 3.8,
    "evening_score": 4.8,
    "formal_score": 4.6,
    "best_temperature": "8°C",
    "related_fragrances": ["Al Nashama Caprice", "SNOI", "Spectre Ghost", "Encre Noire l'Extreme"],
    "description": "An intense, masterfully crafted Italian creation centered on a highly exotic saffron accord, rich rugged leather, and deep amber core spices."
  }
];