export const individualFragrances = [
  {
    "id": 1,
    "name": "SNOI (Supremacy Not Only Intense)",
    "rating": 4.6,
    "inspiration": "Aventus × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Blackcurrant", "Bergamot", "Apple", "Oakmoss", "Saffron"],
    "projection": 4.6,
    "longevity": 4.8,
    "versatility": 4.4,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.4,
    "night_score": 4.6,
    "office_score": 4.1,
    "casual_score": 4.5,
    "evening_score": 4.7,
    "formal_score": 4.4,
    "best_temperature": "8°C–26°C",
    "related_fragrances": ["Supremacy Collector's Edition", "Divin Asylum", "Costume National I"],
    "description": "A powerful Aventus × Hacivat-style extrait with tart blackcurrant, bergamot, apple, dense oakmoss and saffron. Strong projection and excellent longevity make it best for confident day-to-night wear, especially in mild to cool weather."
  },
  {
    "id": 2,
    "name": "Supremacy Collector's Edition",
    "rating": 4.5,
    "inspiration": "Aventus Absolu × Hacivat Hybrid",
    "clone_type": "Hybrid",
    "fragrance_family": "Chypre Fruity",
    "dominant_notes": ["Pineapple", "Bergamot", "Apple", "Birch", "Oakmoss"],
    "projection": 4.3,
    "longevity": 4.4,
    "versatility": 4.6,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Summer", "Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.6,
    "night_score": 4.4,
    "office_score": 4.4,
    "casual_score": 4.7,
    "evening_score": 4.5,
    "formal_score": 4.2,
    "best_temperature": "10°C–28°C",
    "related_fragrances": ["SNOI", "Divin Asylum", "Al Nashama Caprice"],
    "description": "A cleaner and brighter Supremacy-style fruity chypre with pineapple, apple, bergamot, birch, amber and oakmoss. It is highly versatile, performing well as a daily signature across office, casual and evening settings."
  },
  {
    "id": 3,
    "name": "Supremacy In Heaven",
    "rating": 4.0,
    "inspiration": "Silver Mountain Water",
    "clone_type": "Clone",
    "fragrance_family": "Woody Aromatic",
    "dominant_notes": ["Bergamot", "Mandarin Orange", "Green Tea", "Blackcurrant", "Musk"],
    "projection": 3.5,
    "longevity": 3.8,
    "versatility": 4.1,
    "compliment_factor": 4.0,
    "seasons": ["Spring", "Summer"],
    "time_of_day": ["Day"],
    "occasion": ["Office", "Casual", "Gym"],
    "day_score": 4.5,
    "night_score": 3.2,
    "office_score": 4.4,
    "casual_score": 4.3,
    "evening_score": 3.3,
    "formal_score": 3.4,
    "best_temperature": "18°C–32°C",
    "related_fragrances": ["CDNI Milestone", "Liam Grey", "Encre Noire l'Extreme"],
    "description": "A fresh Silver Mountain Water-inspired scent with bergamot, mandarin, green tea, blackcurrant, musk and soft woods. Best for spring and summer daytime wear when you want something clean, airy and unobtrusive."
  },
  {
    "id": 4,
    "name": "Turathi Blue",
    "rating": 4.5,
    "inspiration": "Tygar",
    "clone_type": "Clone",
    "fragrance_family": "Aromatic Citrus",
    "dominant_notes": ["Bergamot", "Mandarin", "Amber", "Woody Notes", "Musk"],
    "projection": 4.2,
    "longevity": 4.3,
    "versatility": 4.7,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Gym"],
    "day_score": 4.8,
    "night_score": 4.1,
    "office_score": 4.6,
    "casual_score": 4.8,
    "evening_score": 4.2,
    "formal_score": 3.8,
    "best_temperature": "16°C–34°C",
    "related_fragrances": ["Jean Lowe Immortal", "Al Nashama Caprice", "CDNI Milestone"],
    "description": "A bright Tygar-style citrus amber with bergamot, mandarin, amber woods, musk, patchouli and fresh spices. It is one of the most versatile warm-weather options here, working especially well for office, casual, gym and relaxed evening wear."
  },
  {
    "id": 5,
    "name": "Al Nashama Caprice",
    "rating": 4.4,
    "inspiration": "Bleu Électrique",
    "clone_type": "Clone",
    "fragrance_family": "Woody Spicy",
    "dominant_notes": ["Cardamom", "Ginger", "Lavender", "Mint", "Amber"],
    "projection": 4.0,
    "longevity": 4.2,
    "versatility": 4.7,
    "compliment_factor": 4.7,
    "seasons": ["Spring", "Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Casual", "Office", "Evening", "Formal"],
    "day_score": 4.3,
    "night_score": 4.6,
    "office_score": 4.5,
    "casual_score": 4.7,
    "evening_score": 4.7,
    "formal_score": 4.3,
    "best_temperature": "8°C–24°C",
    "related_fragrances": ["Turathi Blue", "Costume National I", "Hercules"],
    "description": "A Bleu Électrique-inspired aromatic spicy scent with cardamom, ginger, citrus, lavender, mint, amber and woods. It is polished, versatile and easy to dress up or down, with its best performance in mild to cool weather."
  },
  {
    "id": 6,
    "name": "Jean Lowe Immortal",
    "rating": 4.5,
    "inspiration": "L'Immensité",
    "clone_type": "Clone",
    "fragrance_family": "Woody Aromatic",
    "dominant_notes": ["Ginger", "Grapefruit", "Bergamot", "Ambroxan", "Rosemary"],
    "projection": 4.0,
    "longevity": 4.2,
    "versatility": 4.6,
    "compliment_factor": 4.6,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Office", "Casual", "Evening", "Gym"],
    "day_score": 4.7,
    "night_score": 4.1,
    "office_score": 4.6,
    "casual_score": 4.7,
    "evening_score": 4.2,
    "formal_score": 4.0,
    "best_temperature": "16°C–30°C",
    "related_fragrances": ["Turathi Blue", "Divin Asylum", "Spectre Ghost"],
    "description": "A fresh L'Immensité-inspired aromatic built around ginger, grapefruit, bergamot, rosemary, sage, ambroxan and amber. Clean, modern and versatile, it works best in spring, summer and mild autumn for office, casual and relaxed evening use."
  },
  {
    "id": 7,
    "name": "Divin Asylum",
    "rating": 4.2,
    "inspiration": "Elysium Parfum Cologne",
    "clone_type": "Clone",
    "fragrance_family": "Citrus Aromatic",
    "dominant_notes": ["Grapefruit", "Lime", "Lemon", "Vetiver", "Ambergris"],
    "projection": 3.5,
    "longevity": 3.6,
    "versatility": 4.6,
    "compliment_factor": 4.5,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Casual", "Office", "Formal"],
    "day_score": 4.8,
    "night_score": 3.7,
    "office_score": 4.5,
    "casual_score": 4.6,
    "evening_score": 3.8,
    "formal_score": 4.2,
    "best_temperature": "16°C–30°C",
    "related_fragrances": ["Jean Lowe Immortal", "Liam Grey", "Supremacy Collector's Edition"],
    "description": "A refined Elysium-style citrus aromatic with grapefruit, lemon, lime, vetiver, woods, ambergris, leather and resins. The scent quality is excellent, but projection and longevity are moderate, making it best for daytime office, smart casual and warm-to-mild weather."
  },
  {
    "id": 8,
    "name": "CDNI Milestone",
    "rating": 4.2,
    "inspiration": "Millésime Impérial",
    "clone_type": "Clone",
    "fragrance_family": "Woody Floral Musk",
    "dominant_notes": ["Sea Notes", "Red Fruits", "Bergamot", "Violet", "Musk"],
    "projection": 4.0,
    "longevity": 4.2,
    "versatility": 4.4,
    "compliment_factor": 4.4,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Casual", "Office", "Formal"],
    "day_score": 4.7,
    "night_score": 3.8,
    "office_score": 4.3,
    "casual_score": 4.6,
    "evening_score": 3.8,
    "formal_score": 3.9,
    "best_temperature": "18°C–34°C",
    "related_fragrances": ["Supremacy In Heaven", "Turathi Blue", "SNOI"],
    "description": "A Millésime Impérial-inspired marine musk with sea notes, red fruits, bergamot, violet, white woods, musk and ambroxan. It is salty, fruity and airy, making it ideal for spring and summer daytime wear with enough performance for office and casual use."
  },
  {
    "id": 9,
    "name": "Ash'aa Oud Noir",
    "rating": 4.1,
    "inspiration": "Green Irish Tweed",
    "clone_type": "Clone",
    "fragrance_family": "Aromatic Woody",
    "dominant_notes": ["Bergamot", "Juniper Berry", "Violet", "Mint", "Sandalwood"],
    "projection": 3.8,
    "longevity": 4.0,
    "versatility": 4.3,
    "compliment_factor": 4.1,
    "seasons": ["Spring", "Summer", "Autumn"],
    "time_of_day": ["Day"],
    "occasion": ["Office", "Formal", "Casual"],
    "day_score": 4.5,
    "night_score": 3.5,
    "office_score": 4.5,
    "casual_score": 4.2,
    "evening_score": 3.6,
    "formal_score": 4.2,
    "best_temperature": "12°C–26°C",
    "related_fragrances": ["Jean Lowe Immortal", "Divin Asylum", "Supremacy Collector's Edition"],
    "description": "A Green Irish Tweed-inspired aromatic woody scent with bergamot, juniper, violet, mint, lavender, sandalwood, moss and amber. Despite the name, it wears more fresh-green and woody than oud-heavy, making it best for daytime office, formal and smart casual use."
  },
  {
    "id": 10,
    "name": "Liam Grey",
    "rating": 4.4,
    "inspiration": "Gris Charnel",
    "clone_type": "Clone",
    "fragrance_family": "Amber Spicy",
    "dominant_notes": ["Cardamom", "Black Tea", "Fig", "Iris", "Sandalwood"],
    "projection": 3.9,
    "longevity": 4.3,
    "versatility": 4.6,
    "compliment_factor": 4.5,
    "seasons": ["Autumn", "Winter", "Spring"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Office", "Evening", "Formal", "Casual"],
    "day_score": 4.3,
    "night_score": 4.5,
    "office_score": 4.5,
    "casual_score": 4.5,
    "evening_score": 4.6,
    "formal_score": 4.3,
    "best_temperature": "6°C–22°C",
    "related_fragrances": ["Divin Asylum", "Supremacy In Heaven", "Encre Noire l'Extreme", "Hercules"],
    "description": "A Gris Charnel-inspired woody spicy fragrance with cardamom, black tea, fig, iris, sandalwood, vanilla and tonka. Creamy, refined and unisex, it works beautifully in cool weather across office, casual, formal and evening settings."
  },
  {
    "id": 11,
    "name": "Spectre Ghost",
    "rating": 4.5,
    "inspiration": "Ani",
    "clone_type": "Clone",
    "fragrance_family": "Amber Floral",
    "dominant_notes": ["Vanilla", "Ginger", "Bergamot", "Cardamom", "Pink Pepper"],
    "projection": 4.1,
    "longevity": 4.3,
    "versatility": 4.1,
    "compliment_factor": 4.8,
    "seasons": ["Autumn", "Winter", "Spring"],
    "time_of_day": ["Night"],
    "occasion": ["Evening", "Formal", "Casual"],
    "day_score": 3.8,
    "night_score": 4.8,
    "office_score": 3.3,
    "casual_score": 4.2,
    "evening_score": 4.8,
    "formal_score": 4.5,
    "best_temperature": "6°C–20°C",
    "related_fragrances": ["Jean Lowe Immortal", "Hercules", "Costume National I"],
    "description": "An Ani-inspired spicy vanilla scent with ginger, bergamot, cardamom, pink pepper and a creamy ambered base. Warm, sweet and attention-grabbing, it is best reserved for cooler evening wear, dates, dinners and formal nights."
  },
  {
    "id": 12,
    "name": "Hercules",
    "rating": 4.2,
    "inspiration": "Herod",
    "clone_type": "Clone",
    "fragrance_family": "Amber Woody",
    "dominant_notes": ["Tobacco", "Vanilla", "Cinnamon", "Pepper", "Incense"],
    "projection": 3.8,
    "longevity": 4.0,
    "versatility": 3.8,
    "compliment_factor": 4.4,
    "seasons": ["Autumn", "Winter"],
    "time_of_day": ["Night"],
    "occasion": ["Evening", "Formal", "Casual"],
    "day_score": 3.3,
    "night_score": 4.6,
    "office_score": 3.0,
    "casual_score": 4.0,
    "evening_score": 4.6,
    "formal_score": 4.3,
    "best_temperature": "2°C–16°C",
    "related_fragrances": ["Spectre Ghost", "Liam Grey", "Al Nashama Caprice"],
    "description": "A Herod-inspired tobacco vanilla fragrance with cinnamon, pepper, incense and warm woods. It is a cool-weather night scent suited to dinners, dates, formal winter settings and relaxed evening wear."
  },
  {
    "id": 13,
    "name": "Encre Noire l'Extreme",
    "rating": 3.9,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Woody Aromatic",
    "dominant_notes": ["Vetiver", "Cypress", "Elemi", "Incense", "Orris Root"],
    "projection": 4.0,
    "longevity": 4.3,
    "versatility": 3.3,
    "compliment_factor": 3.4,
    "seasons": ["Autumn", "Winter"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Formal", "Evening", "Office"],
    "day_score": 3.8,
    "night_score": 4.3,
    "office_score": 3.8,
    "casual_score": 3.3,
    "evening_score": 4.2,
    "formal_score": 4.4,
    "best_temperature": "4°C–18°C",
    "related_fragrances": ["Turathi Blue", "Liam Grey", "Costume National I", "Supremacy In Heaven"],
    "description": "A dark woody aromatic centred on vetiver, cypress, elemi, incense, orris and dry woods. Austere, earthy and smoky, it is best for autumn and winter office, formal and evening wear rather than casual mass appeal."
  },
  {
    "id": 14,
    "name": "Costume National I",
    "rating": 4.1,
    "inspiration": "Original",
    "clone_type": "Original",
    "fragrance_family": "Amber Leather",
    "dominant_notes": ["Saffron", "Bergamot", "Thyme", "Leather", "Ambroxan"],
    "projection": 4.0,
    "longevity": 4.2,
    "versatility": 4.0,
    "compliment_factor": 4.2,
    "seasons": ["Autumn", "Winter", "Spring"],
    "time_of_day": ["Day", "Night"],
    "occasion": ["Evening", "Formal", "Office", "Casual"],
    "day_score": 3.9,
    "night_score": 4.5,
    "office_score": 3.8,
    "casual_score": 4.0,
    "evening_score": 4.5,
    "formal_score": 4.4,
    "best_temperature": "6°C–22°C",
    "related_fragrances": ["Al Nashama Caprice", "SNOI", "Spectre Ghost", "Encre Noire l'Extreme"],
    "description": "Costume National I is a saffron-led amber leather fragrance with bergamot, thyme, lavender, geranium, labdanum, leather, ambroxan and cedarwood. Smooth, spicy, leathery and modern, it is best in cool to mild weather for evenings, formal wear, confident office use and elevated casual settings."
  }
];
